### ISSUE TITLE
Investigate why some failed primary captures are being labeled with 'success'

### ISSUE THREAD

**Issue by anastasia** [harvard-lil/perma#1971]
https://perma.cc/5KAR-NR2E
https://perma.cc/TY8J-WS5M
https://perma.cc/DRA5-3SRB
https://perma.cc/3TEX-NDDN
...etc.

also interesting to note that they're all 404s to begin with

Internet archive stack trace
```
Traceback (most recent call last):
  File "/srv/www/perma-envs/perma/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/srv/www/perma-envs/perma/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/srv/www/perma/perma_web/perma/tasks.py", line 1020, in upload_to_internet_archive
    verbose=True,
  File "/srv/www/perma-envs/perma/lib/python2.7/site-packages/internetarchive/api.py", line 285, in upload
    request_kwargs=request_kwargs)
  File "/srv/www/perma-envs/perma/lib/python2.7/site-packages/internetarchive/item.py", line 742, in upload
    request_kwargs=request_kwargs)
  File "/srv/www/perma-envs/perma/lib/python2.7/site-packages/internetarchive/item.py", line 630, in upload_file
    msg = get_s3_xml_text(exc.response.content)
  File "/srv/www/perma-envs/perma/lib/python2.7/site-packages/internetarchive/utils.py", line 162, in get_s3_xml_text
    p = parseString(xml_str)
  File "/usr/lib64/python2.7/xml/dom/minidom.py", line 1928, in parseString
    return expatbuilder.parseString(string)
  File "/usr/lib64/python2.7/xml/dom/expatbuilder.py", line 940, in parseString
    return builder.parseString(string)
  File "/usr/lib64/python2.7/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
ExpatError: syntax error: line 1, column 49

```

**Comment by anastasia** [comment]
potentially related, urls of said captures:

https://www.ntanet.org/wp-content/uploads/proceedings/2014/141-phillips-plumley-effort-compliance-endogenous-taxpayer-decisions.pdf�
https://www.irs.gov/pub/irs-pdf/i6251.pdf�
http://www.irs.gov/pub/irs-pdf/f1040sc.pdf�

**Comment by anastasia** [comment]
control character fix merged: https://github.com/harvard-lil/perma/pull/1980
