### ISSUE TITLE
Capture failure not working as desired.

### ISSUE THREAD

**Issue by rebeccacremona** [harvard-lil/perma#1994]
See this capture, which failed on purpose (I set the celery soft time out to 2 seconds). See how far it gets in the capture process, but see the error the user gets. I don't think this is how it is supposed to work:

[2017-04-27 14:49:12,287: WARNING/Worker-2] EQH9-75QK: Fetching http://example.com
[2017-04-27 14:49:12,290: WARNING/Worker-2] EQH9-75QK step 0: Starting capture
[2017-04-27 14:49:12,473: WARNING/Worker-2] WarcProx opened.
[2017-04-27 14:49:12,476: WARNING/Worker-2] EQH9-75QK step 1: Fetching target URL
[2017-04-27 14:49:13,790: WARNING/Worker-2] Finished fetching url.
[2017-04-27 14:49:13,794: WARNING/Worker-2] EQH9-75QK step 2: Checking x-robots-tag directives.
[2017-04-27 14:49:13,801: WARNING/Worker-2] Checking meta tags.
[2017-04-27 14:49:13,802: WARNING/Worker-2] Fetching robots.txt ...
[2017-04-27 14:49:13,806: WARNING/Worker-2] EQH9-75QK step 3: Getting page title
[2017-04-27 14:49:13,881: WARNING/Worker-2] Couldn't reach robots.txt
[2017-04-27 14:49:13,952: WARNING/Worker-2] EQH9-75QK step 3.5: Checking for scroll-loaded assets
[2017-04-27 14:49:14,070: WARNING/Worker-2] EQH9-75QK step 4: Fetching media
[2017-04-27 14:49:14,098: WARNING/Worker-2] Fetching images in srcsets
[2017-04-27 14:49:14,142: WARNING/Worker-2] Fetching favicon from http://example.com/favicon.ico ...
[2017-04-27 14:49:14,162: WARNING/Worker-2] EQH9-75QK step 5: Waiting for post-load requests
[2017-04-27 14:49:14,187: WARNING/Worker-2] Favicon failed:
[2017-04-27 14:49:14,187: WARNING/Worker-2] None
[2017-04-27 14:49:14,187: WARNING/Worker-2] <Response [404]>
[2017-04-27 14:49:14,188: WARNING/Worker-2] Couldn't get favicon
[2017-04-27 14:49:14,215: WARNING/MainProcess] Soft time limit (2s) exceeded for perma.tasks.run_next_capture[805855fd-d8c8-4ee6-b71c-50d58c6be492]
[2017-04-27 14:49:14,220: WARNING/Worker-2] Shutting down browser and proxies.

![timeout](https://cloud.githubusercontent.com/assets/11020492/25489544/1f3f3c00-2b38-11e7-9b93-981e872e1216.png)

**Comment by rebeccacremona** [comment]
Ooh. And capture didn't utterly bail and fail to save either.... it failed very similarly to these https://github.com/harvard-lil/perma/issues/1991

![screenshot-worked](https://cloud.githubusercontent.com/assets/11020492/25490173/09db4582-2b3a-11e7-91d1-bd83f31f5fdb.png)

**Comment by rebeccacremona** [comment]
If the timeout/failure happens after "Writing CDX lines to the DB", you have a successful playback, but you get the same yellow error. However, on refresh, the link is not marked as a failed capture (new gray styling, etc.), and when you click on it, all is well. The "capture job" is marked as failed, as expected.

**Comment by rebeccacremona** [comment]
While writing CDX lines to the DB:
```
2017-04-27 16:22:59,274: WARNING/Worker-2] TN3K-3N39: Fetching http://example.com
[2017-04-27 16:22:59,278: WARNING/Worker-2] TN3K-3N39 step 0: Starting capture
[2017-04-27 16:22:59,631: WARNING/Worker-2] WarcProx opened.
[2017-04-27 16:22:59,633: WARNING/Worker-2] TN3K-3N39 step 1: Fetching target URL
[2017-04-27 16:23:00,817: WARNING/Worker-2] Finished fetching url.
[2017-04-27 16:23:00,820: WARNING/Worker-2] TN3K-3N39 step 2: Checking x-robots-tag directives.
[2017-04-27 16:23:00,829: WARNING/Worker-2] Checking meta tags.
[2017-04-27 16:23:00,831: WARNING/Worker-2] Fetching robots.txt ...
[2017-04-27 16:23:00,834: WARNING/Worker-2] TN3K-3N39 step 3: Getting page title
[2017-04-27 16:23:00,908: WARNING/Worker-2] TN3K-3N39 step 3.5: Checking for scroll-loaded assets
[2017-04-27 16:23:00,917: WARNING/Worker-2] Couldn't reach robots.txt
[2017-04-27 16:23:00,973: WARNING/Worker-2] TN3K-3N39 step 4: Fetching media
[2017-04-27 16:23:00,999: WARNING/Worker-2] Fetching images in srcsets
[2017-04-27 16:23:01,044: WARNING/Worker-2] Fetching favicon from http://example.com/favicon.ico ...
[2017-04-27 16:23:01,055: WARNING/Worker-2] TN3K-3N39 step 5: Waiting for post-load requests
[2017-04-27 16:23:01,134: WARNING/Worker-2] Favicon failed:
[2017-04-27 16:23:01,134: WARNING/Worker-2] None
[2017-04-27 16:23:01,134: WARNING/Worker-2] <Response [404]>
[2017-04-27 16:23:01,134: WARNING/Worker-2] Couldn't get favicon
[27/Apr/2017 16:23:01] "GET /api/v2/user/capture_jobs/TN3K-3N39/ HTTP/1.1" 200 211
[2017-04-27 16:23:01,630: WARNING/Worker-2] TN3K-3N39 step 6: Taking screenshot
[2017-04-27 16:23:01,792: WARNING/Worker-2] Shutting down browser and proxies.
[2017-04-27 16:23:02,576: WARNING/Worker-2] TN3K-3N39 step 7: Saving web archive file
[2017-04-27 16:23:02,587: WARNING/Worker-2] Writing CDX lines to the DB
[2017-04-27 16:23:02,610: WARNING/MainProcess] Soft time limit (3.4s) exceeded for perma.tasks.run_next_capture[5ff96cbe-dd82-401e-a870-9b9f392755a2]
[2017-04-27 16:23:02,731: WARNING/Worker-2] Exception while processing capture job TN3K-3N39:
[2017-04-27 16:23:02,735: WARNING/Worker-2] Traceback (most recent call last):
[2017-04-27 16:23:02,738: WARNING/Worker-2] File "/vagrant/perma_web/perma/tasks.py", line 318, in run_next_capture
[2017-04-27 16:23:02,745: WARNING/Worker-2] proxy_capture(capture_job)
[2017-04-27 16:23:02,747: WARNING/Worker-2] File "/home/vagrant/.virtualenvs/perma/local/lib/python2.7/site-packages/tempdir.py", line 60, in wrapper
[2017-04-27 16:23:02,748: WARNING/Worker-2] return fnc(*funcargs, **funckwargs)
[2017-04-27 16:23:02,749: WARNING/Worker-2] File "/vagrant/perma_web/perma/tasks.py", line 850, in proxy_capture
[2017-04-27 16:23:02,751: WARNING/Worker-2] CDXLine.objects.create_all_from_link(link)
[2017-04-27 16:23:02,752: WARNING/Worker-2] File "/vagrant/perma_web/perma/models.py", line 1290, in create_all_from_link
[2017-04-27 16:23:02,757: WARNING/Worker-2] cdxline = CDXLine.objects.get_or_create(raw=line, link_id=link.guid)[0]
[2017-04-27 16:23:02,758: WARNING/Worker-2] File "/home/vagrant/.virtualenvs/perma/local/lib/python2.7/site-packages/django/db/models/manager.py", line 122, in manager_method
[2017-04-27 16:23:02,760: WARNING/Worker-2] return getattr(self.get_queryset(), name)(*args, **kwargs)
[2017-04-27 16:23:02,761: WARNING/Worker-2] File "/home/vagrant/.virtualenvs/perma/local/lib/python2.7/site-packages/django/db/models/query.py", line 465, in get_or_create
[2017-04-27 16:23:02,763: WARNING/Worker-2] return self.get(**lookup), False
[2017-04-27 16:23:02,764: WARNING/Worker-2] File "/home/vagrant/.virtualenvs/perma/local/lib/python2.7/site-packages/django/db/models/query.py", line 381, in get
[2017-04-27 16:23:02,765: WARNING/Worker-2] num = len(clone)
[2017-04-27 16:23:02,770: WARNING/Worker-2] File "/home/vagrant/.virtualenvs/perma/local/lib/python2.7/site-packages/django/db/models/query.py", line 240, in __len__
[2017-04-27 16:23:02,772: WARNING/Worker-2] self._fetch_all()
[2017-04-27 16:23:02,773: WARNING/Worker-2] File "/home/vagrant/.virtualenvs/perma/local/lib/python2.7/site-packages/django/db/models/query.py", line 1074, in _fetch_all
[2017-04-27 16:23:02,774: WARNING/Worker-2] self._result_cache = list(self.iterator())
[2017-04-27 16:23:02,775: WARNING/Worker-2] File "/home/vagrant/.virtualenvs/perma/local/lib/python2.7/site-packages/django/db/models/query.py", line 52, in __iter__
[2017-04-27 16:23:02,776: WARNING/Worker-2] results = compiler.execute_sql()
[2017-04-27 16:23:02,777: WARNING/Worker-2] File "/home/vagrant/.virtualenvs/perma/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 850, in execute_sql
[2017-04-27 16:23:02,779: WARNING/Worker-2] cursor.close()
[2017-04-27 16:23:02,780: WARNING/Worker-2] File "/home/vagrant/.virtualenvs/perma/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 100, in close
[2017-04-27 16:23:02,784: WARNING/Worker-2] while self.nextset(): pass
[2017-04-27 16:23:02,785: WARNING/Worker-2] File "/home/vagrant/.virtualenvs/perma/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 132, in nextset
[2017-04-27 16:23:02,788: WARNING/Worker-2] nr = db.next_result()
[2017-04-27 16:23:02,789: WARNING/Worker-2] ProgrammingError: (2014, "Commands out of sync; you can't run this command now")
[2017-04-27 16:23:02,835: WARNING/Worker-2] Exception
[2017-04-27 16:23:02,837: INFO/MainProcess] Received task: perma.tasks.run_next_capture[c4d7162a-dbf6-4667-ab68-cad5453a1f5a]
[2017-04-27 16:23:02,839: WARNING/Worker-2] _mysql_exceptions
[2017-04-27 16:23:02,840: WARNING/Worker-2] .
[2017-04-27 16:23:02,841: WARNING/Worker-2] ProgrammingError
[2017-04-27 16:23:02,842: WARNING/Worker-2] :
[2017-04-27 16:23:02,844: WARNING/Worker-2] (2014, "Commands out of sync; you can't run this command now")
[2017-04-27 16:23:02,844: WARNING/Worker-2] in
[2017-04-27 16:23:02,845: WARNING/Worker-2] <bound method Cursor.__del__ of <MySQLdb.cursors.Cursor object at 0x7f3dde367950>>
[2017-04-27 16:23:02,846: WARNING/Worker-2] ignored
```
Same yellow error, screenshot-only display (of course); warc contains all needed resources (of course). When I toggle the primary capture to "succeeded", playback seems to be fine (does that mean the db actually has all the cdxlines we need, by luck?)

**Comment by rebeccacremona** [comment]
Manually dove into the below using rdb:
```
   def close_warc_after_writing(self, out):
        out.flush()
        out.seek(0)
        default_storage.store_file(out, self.warc_storage_file(), overwrite=True)
        out.close()
```
If you contrive a partial write, inside  default_storage.store_file, you can arrange for a truncated warc that looks just like our LOCKSS-reported failures.
