### ISSUE TITLE
Forbes

### ISSUE THREAD

**Issue by rebeccacremona** [harvard-lil/perma#2029]
Let's keep our eye on whether the Forbes special function is working:

```
Exception while processing capture job Z6XM-DCDB:
Traceback (most recent call last):
  File "/vagrant/perma_web/perma/tasks.py", line 1000, in run_next_capture
    post_load_function(browser)
  File "/vagrant/perma_web/perma/site_scripts.py", line 11, in forbes_post_load
    browser.find_element_by_css_selector('.continue-button').click()
  File "/home/vagrant/.virtualenvs/perma/local/lib/python2.7/site-packages/selenium/webdriver/remote/webelement.py", line 74, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/vagrant/.virtualenvs/perma/local/lib/python2.7/site-packages/selenium/webdriver/remote/webelement.py", line 453, in _execute
    return self._parent.execute(command, params)
  File "/home/vagrant/.virtualenvs/perma/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 201, in execute
    self.error_handler.check_response(response)
  File "/home/vagrant/.virtualenvs/perma/local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 181, in check_response
    raise exception_class(message, screen, stacktrace)
TimeoutException: Message: {"errorMessage":"Click failed: timeout","request":{"headers":{"Accept":"application/json","Accept-Encoding":"identity","Connection":"close","Content-Length":"81","Content-Type":"application/json;charset=UTF-8","Host":"127.0.0.1:51788","User-Agent":"Python-urllib/2.7"},"httpVersion":"1.1","method":"POST","post":"{\"sessionId\": \"f4278fd0-3b2d-11e7-98bc-370f60d94119\", \"id\": \":wdc:1495045446480\"}","url":"/click","urlParsed":{"anchor":"","query":"","file":"click","directory":"/","path":"/click","relative":"/click","port":"","host":"","password":"","user":"","userInfo":"","authority":"","protocol":"","source":"/click","queryKey":{},"chunks":["click"]},"urlOriginal":"/session/f4278fd0-3b2d-11e7-98bc-370f60d94119/element/:wdc:1495045446480/click"}}
```

**Comment by rebeccacremona** [comment]
Okay, never mind: I have now seen at least one instance where it does indeed click continue. I believe the click is so slow, after reading a bunch of StackOverflow posts, that a virtual cursor is moved, slowly slowly slowly to actually click on the found element.
