### ISSUE TITLE
perma-dev too many DB connections

### ISSUE THREAD

**Issue by rebeccacremona** [harvard-lil/perma#2451]
Error like this during playback, when I was intentionally trying to tax dev by capturing/playback CNN and Twitter at the same time:
```
[ERROR] pywb_config.py 139: Internal Server Error (pywb): /warc/87PN-SVT4/20180816182247///cdn.cnn.com/cnnnext/dam/assets/171124002227-black-friday-shopping-2017-exlarge-tease.jpg

2018-08-16T18:26:46.275827+00:00 app[web.1]: Traceback (most recent call last):

2018-08-16T18:26:46.275831+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection

2018-08-16T18:26:46.275833+00:00 app[web.1]:     self.connect()

2018-08-16T18:26:46.275835+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/db/backends/base/base.py", line 189, in connect

2018-08-16T18:26:46.275838+00:00 app[web.1]:     self.connection = self.get_new_connection(conn_params)

2018-08-16T18:26:46.275839+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 274, in get_new_connection

2018-08-16T18:26:46.275841+00:00 app[web.1]:     conn = Database.connect(**conn_params)

2018-08-16T18:26:46.275843+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/MySQLdb/__init__.py", line 86, in Connect

2018-08-16T18:26:46.275844+00:00 app[web.1]:     return Connection(*args, **kwargs)

2018-08-16T18:26:46.275846+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/MySQLdb/connections.py", line 204, in __init__

2018-08-16T18:26:46.275848+00:00 app[web.1]:     super(Connection, self).__init__(*args, **kwargs2)

2018-08-16T18:26:46.275850+00:00 app[web.1]: _mysql_exceptions.OperationalError: (1040, 'Too many connections')

2018-08-16T18:26:46.275852+00:00 app[web.1]: 

2018-08-16T18:26:46.275854+00:00 app[web.1]: The above exception was the direct cause of the following exception:

2018-08-16T18:26:46.275855+00:00 app[web.1]: 

2018-08-16T18:26:46.275857+00:00 app[web.1]: Traceback (most recent call last):

2018-08-16T18:26:46.275859+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/pywb/framework/wsgi_wrappers.py", line 65, in handle_methods

2018-08-16T18:26:46.275860+00:00 app[web.1]:     response = wb_router(env)

2018-08-16T18:26:46.275862+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/pywb/framework/archivalrouter.py", line 41, in __call__

2018-08-16T18:26:46.275864+00:00 app[web.1]:     use_abs_prefix=self.abs_path)

2018-08-16T18:26:46.275866+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/pywb/framework/archivalrouter.py", line 84, in parse_request

2018-08-16T18:26:46.275867+00:00 app[web.1]:     route.apply_filters(wbrequest, matcher)

2018-08-16T18:26:46.275869+00:00 app[web.1]:   File "/app/warc_server/pywb_config.py", line 162, in apply_filters



*******
2018-08-16T18:26:46.275871+00:00 app[web.1]:     link = Link.objects.get(guid=guid)
*******



2018-08-16T18:26:46.275873+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method

2018-08-16T18:26:46.275875+00:00 app[web.1]:     return getattr(self.get_queryset(), name)(*args, **kwargs)

2018-08-16T18:26:46.275876+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/db/models/query.py", line 374, in get

2018-08-16T18:26:46.275878+00:00 app[web.1]:     num = len(clone)

2018-08-16T18:26:46.275880+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/db/models/query.py", line 232, in __len__

2018-08-16T18:26:46.275881+00:00 app[web.1]:     self._fetch_all()

2018-08-16T18:26:46.275883+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/db/models/query.py", line 1118, in _fetch_all

2018-08-16T18:26:46.275885+00:00 app[web.1]:     self._result_cache = list(self._iterable_class(self))

2018-08-16T18:26:46.275887+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/db/models/query.py", line 53, in __iter__

2018-08-16T18:26:46.275888+00:00 app[web.1]:     results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)

2018-08-16T18:26:46.275890+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 876, in execute_sql

2018-08-16T18:26:46.275892+00:00 app[web.1]:     sql, params = self.as_sql()

2018-08-16T18:26:46.275894+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 441, in as_sql

2018-08-16T18:26:46.275896+00:00 app[web.1]:     where, w_params = self.compile(self.where) if self.where is not None else ("", [])

2018-08-16T18:26:46.275898+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 373, in compile

2018-08-16T18:26:46.275899+00:00 app[web.1]:     sql, params = node.as_sql(self, self.connection)

2018-08-16T18:26:46.275901+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/db/models/sql/where.py", line 79, in as_sql

2018-08-16T18:26:46.275902+00:00 app[web.1]:     sql, params = compiler.compile(child)

2018-08-16T18:26:46.275904+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 373, in compile

2018-08-16T18:26:46.275906+00:00 app[web.1]:     sql, params = node.as_sql(self, self.connection)

2018-08-16T18:26:46.275908+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/db/models/lookups.py", line 169, in as_sql

2018-08-16T18:26:46.275909+00:00 app[web.1]:     lhs_sql, params = self.process_lhs(compiler, connection)

2018-08-16T18:26:46.275911+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/db/models/lookups.py", line 162, in process_lhs

2018-08-16T18:26:46.275913+00:00 app[web.1]:     db_type = self.lhs.output_field.db_type(connection=connection)

2018-08-16T18:26:46.275915+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 644, in db_type

2018-08-16T18:26:46.275917+00:00 app[web.1]:     return connection.data_types[self.get_internal_type()] % data

2018-08-16T18:26:46.275918+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/utils/functional.py", line 35, in __get__

2018-08-16T18:26:46.275920+00:00 app[web.1]:     res = instance.__dict__[self.name] = self.func(instance)

2018-08-16T18:26:46.275930+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 174, in data_types

2018-08-16T18:26:46.275932+00:00 app[web.1]:     if self.features.supports_microsecond_precision:

2018-08-16T18:26:46.275933+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/utils/functional.py", line 35, in __get__

2018-08-16T18:26:46.275935+00:00 app[web.1]:     res = instance.__dict__[self.name] = self.func(instance)

2018-08-16T18:26:46.275939+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/db/backends/mysql/features.py", line 53, in supports_microsecond_precision

2018-08-16T18:26:46.275941+00:00 app[web.1]:     return self.connection.mysql_version >= (5, 6, 4) and Database.version_info >= (1, 2, 5)

2018-08-16T18:26:46.275942+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/utils/functional.py", line 35, in __get__

2018-08-16T18:26:46.275944+00:00 app[web.1]:     res = instance.__dict__[self.name] = self.func(instance)

2018-08-16T18:26:46.275946+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 385, in mysql_version

2018-08-16T18:26:46.275948+00:00 app[web.1]:     with self.temporary_connection() as cursor:

2018-08-16T18:26:46.275950+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/contextlib.py", line 81, in __enter__

2018-08-16T18:26:46.275952+00:00 app[web.1]:     return next(self.gen)

2018-08-16T18:26:46.275953+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/db/backends/base/base.py", line 591, in temporary_connection

2018-08-16T18:26:46.275955+00:00 app[web.1]:     cursor = self.cursor()

2018-08-16T18:26:46.275957+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/db/backends/base/base.py", line 254, in cursor

2018-08-16T18:26:46.275958+00:00 app[web.1]:     return self._cursor()

2018-08-16T18:26:46.275960+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/db/backends/base/base.py", line 229, in _cursor

2018-08-16T18:26:46.275962+00:00 app[web.1]:     self.ensure_connection()

2018-08-16T18:26:46.275963+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection

2018-08-16T18:26:46.275965+00:00 app[web.1]:     self.connect()

2018-08-16T18:26:46.275967+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/db/utils.py", line 94, in __exit__

2018-08-16T18:26:46.275968+00:00 app[web.1]:     six.reraise(dj_exc_type, dj_exc_value, traceback)

2018-08-16T18:26:46.275970+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise

2018-08-16T18:26:46.275972+00:00 app[web.1]:     raise value.with_traceback(tb)

2018-08-16T18:26:46.275974+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection

2018-08-16T18:26:46.275975+00:00 app[web.1]:     self.connect()

2018-08-16T18:26:46.275977+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/db/backends/base/base.py", line 189, in connect

2018-08-16T18:26:46.275979+00:00 app[web.1]:     self.connection = self.get_new_connection(conn_params)

2018-08-16T18:26:46.275980+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 274, in get_new_connection

2018-08-16T18:26:46.275982+00:00 app[web.1]:     conn = Database.connect(**conn_params)

2018-08-16T18:26:46.275983+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/MySQLdb/__init__.py", line 86, in Connect

2018-08-16T18:26:46.275985+00:00 app[web.1]:     return Connection(*args, **kwargs)

2018-08-16T18:26:46.275987+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/MySQLdb/connections.py", line 204, in __init__

2018-08-16T18:26:46.275989+00:00 app[web.1]:     super(Connection, self).__init__(*args, **kwargs2)

2018-08-16T18:26:46.275990+00:00 app[web.1]: django.db.utils.OperationalError: (1040, 'Too many connections')

2018-08-16T18:26:46.582560+00:00 app[web.1]:     if self.features.supports_microsecond_precision:

2018-08-16T18:26:46.582571+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/utils/functional.py", line 35, in __get__

2018-08-16T18:26:46.582572+00:00 app[web.1]:     res = instance.__dict__[self.name] = self.func(instance)

2018-08-16T18:26:46.582574+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/db/backends/mysql/features.py", line 53, in supports_microsecond_precision

2018-08-16T18:26:46.582576+00:00 app[web.1]:     return self.connection.mysql_version >= (5, 6, 4) and Database.version_info >= (1, 2, 5)

2018-08-16T18:26:46.582578+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/utils/functional.py", line 35, in __get__

2018-08-16T18:26:46.582581+00:00 app[web.1]:     res = instance.__dict__[self.name] = self.func(instance)

2018-08-16T18:26:46.582583+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 385, in mysql_version

2018-08-16T18:26:46.582585+00:00 app[web.1]:     with self.temporary_connection() as cursor:

2018-08-16T18:26:46.582586+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/contextlib.py", line 81, in __enter__

2018-08-16T18:26:46.582588+00:00 app[web.1]:     return next(self.gen)

2018-08-16T18:26:46.582590+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/db/backends/base/base.py", line 591, in temporary_connection

2018-08-16T18:26:46.582591+00:00 app[web.1]:     cursor = self.cursor()

2018-08-16T18:26:46.582593+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/db/backends/base/base.py", line 254, in cursor

2018-08-16T18:26:46.582594+00:00 app[web.1]:     return self._cursor()

2018-08-16T18:26:46.582596+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/db/backends/base/base.py", line 229, in _cursor

2018-08-16T18:26:46.582597+00:00 app[web.1]:     self.ensure_connection()

2018-08-16T18:26:46.582599+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection

2018-08-16T18:26:46.582601+00:00 app[web.1]:     self.connect()

2018-08-16T18:26:46.582602+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/db/utils.py", line 94, in __exit__

2018-08-16T18:26:46.582604+00:00 app[web.1]:     six.reraise(dj_exc_type, dj_exc_value, traceback)

2018-08-16T18:26:46.582605+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise

2018-08-16T18:26:46.582607+00:00 app[web.1]:     raise value.with_traceback(tb)

2018-08-16T18:26:46.582608+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection

2018-08-16T18:26:46.582610+00:00 app[web.1]:     self.connect()

2018-08-16T18:26:46.582612+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/db/backends/base/base.py", line 189, in connect

2018-08-16T18:26:46.582613+00:00 app[web.1]:     self.connection = self.get_new_connection(conn_params)

2018-08-16T18:26:46.582615+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 274, in get_new_connection

2018-08-16T18:26:46.582617+00:00 app[web.1]:     conn = Database.connect(**conn_params)

2018-08-16T18:26:46.582618+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/MySQLdb/__init__.py", line 86, in Connect

2018-08-16T18:26:46.582620+00:00 app[web.1]:     return Connection(*args, **kwargs)

2018-08-16T18:26:46.582621+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/MySQLdb/connections.py", line 204, in __init__

2018-08-16T18:26:46.582623+00:00 app[web.1]:     super(Connection, self).__init__(*args, **kwargs2)

2018-08-16T18:26:46.585010+00:00 app[web.1]: django.db.utils.OperationalError: (1040, 'Too many connections')
```

**Comment by rebeccacremona** [comment]
No longer relevant: this heroku tier is retired, as is custom pywb playback,
