### ISSUE TITLE
Don't die if content_type not provided

### ISSUE THREAD

**Issue by rebeccacremona** [harvard-lil/perma#2453]
http://mfa.gov.il/ProtectiveEdge/Documents/PalestinianFatalities.pdf
```
7KV8-AMXN step 0: Starting capture
WarcProx opened.
Using browser: PhantomJS
7KV8-AMXN step 1: Fetching target URL
7KV8-AMXN step 1.02621644337972: Fetching target URL
Exception while capturing job 7KV8-AMXN:
Traceback (most recent call last):
  File "/perma/perma_web/perma/tasks.py", line 982, in run_next_capture
    content_type = response.content_type.lower()
AttributeError: 'NoneType' object has no attribute 'lower'
Shutting down browser and proxies.
7KV8-AMXN step 2: Saving web archive file
Exception while tearing down/saving capture job 7KV8-AMXN:
Traceback (most recent call last):
  File "/perma/perma_web/perma/tasks.py", line 1116, in run_next_capture
    save_warc(warcprox_controller, capture_job, link, content_type, screenshot, successful_favicon_urls)
UnboundLocalError: local variable 'content_type' referenced before assignment
```

**Comment by rebeccacremona** [comment]
https://www.healthaffairs.org/do/10.1377/hpb20180116.967310/full/HPP_2018_CMWF_02_W.pdf too
