### ISSUE TITLE
Another `.gov` failed capture

### ISSUE THREAD

**Issue by rebeccacremona** [harvard-lil/perma#2567]
Repeatable.
```
9RPK-XAAH step 0: Starting capture
WarcProx opened.
Using browser: PhantomJS
9RPK-XAAH step 1: Fetching target URL
9RPK-XAAH step 1.0247346348232693: Fetching target URL
9RPK-XAAH step 1.0471776061587863: Fetching target URL
9RPK-XAAH step 1.0695682419670953: Fetching target URL
9RPK-XAAH step 1.0920338683658175: Fetching target URL
9RPK-XAAH step 1.1145042101542155: Fetching target URL
9RPK-XAAH step 1.1369556585947673: Fetching target URL
9RPK-XAAH step 1.1594079441494411: Fetching target URL
9RPK-XAAH step 1.1820667955610487: Fetching target URL
9RPK-XAAH step 1.2046049647861057: Fetching target URL
9RPK-XAAH step 1.2270880116356744: Fetching target URL
9RPK-XAAH step 1.2495449754926893: Fetching target URL
9RPK-XAAH step 1.272088845570882: Fetching target URL
9RPK-XAAH step 1.2945944521162245: Fetching target URL
9RPK-XAAH step 1.3171314769321016: Fetching target URL
9RPK-XAAH step 1.339620574315389: Fetching target URL
9RPK-XAAH step 1.362100887298584: Fetching target URL
9RPK-XAAH step 1.384596994188097: Fetching target URL
9RPK-XAAH step 1.4070710235171848: Fetching target URL
9RPK-XAAH step 1.4291001001993815: Fetching target URL
9RPK-XAAH step 1.4516133043501112: Fetching target URL
9RPK-XAAH step 1.4740697436862522: Fetching target URL
9RPK-XAAH step 1.4965842141045465: Fetching target URL
9RPK-XAAH step 1.5190639866722955: Fetching target URL
9RPK-XAAH step 1.5415630605485704: Fetching target URL
9RPK-XAAH step 1.5640846835242377: Fetching target URL
9RPK-XAAH step 1.5865948359171549: Fetching target URL
9RPK-XAAH step 1.6090492566426595: Fetching target URL
9RPK-XAAH step 1.6315816190507677: Fetching target URL
9RPK-XAAH step 1.6540682050916884: Fetching target URL
9RPK-XAAH step 1.676547204123603: Fetching target URL
Exception in thread page_load:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/root/.local/share/virtualenvs/perma_web-kkDLCj8f/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 213, in get
    self.execute(Command.GET, {'url': url})
  File "/root/.local/share/virtualenvs/perma_web-kkDLCj8f/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 201, in execute
    self.error_handler.check_response(response)
  File "/root/.local/share/virtualenvs/perma_web-kkDLCj8f/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 181, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: {"errorMessage":"URL 'https://taxpayeradvocate.irs.gov/' didn't load. Error: 'timeout'","request":{"headers":{"Accept":"application/json","Accept-Encoding":"identity","Connection":"close","Content-Length":"97","Content-Type":"application/json;charset=UTF-8","Host":"127.0.0.1:56619","User-Agent":"Python-urllib/3.5"},"httpVersion":"1.1","method":"POST","post":"{\"sessionId\": \"5aafbec0-509f-11e9-b6bc-6d72648795e7\", \"url\": \"https://taxpayeradvocate.irs.gov/\"}","url":"/url","urlParsed":{"anchor":"","query":"","file":"url","directory":"/","path":"/url","relative":"/url","port":"","host":"","password":"","user":"","userInfo":"","authority":"","protocol":"","source":"/url","queryKey":{},"chunks":["url"]},"urlOriginal":"/session/5aafbec0-509f-11e9-b6bc-6d72648795e7/url"}}
Screenshot: available via screen


9RPK-XAAH step 1.6990565035078262: Fetching target URL
9RPK-XAAH step 1.721539608637492: Fetching target URL
9RPK-XAAH step 1.7440411037868924: Fetching target URL
9RPK-XAAH step 1.766609377331204: Fetching target URL
9RPK-XAAH step 1.7890795919630262: Fetching target URL
9RPK-XAAH step 1.811481730143229: Fetching target URL
9RPK-XAAH step 1.8339795536465116: Fetching target URL
9RPK-XAAH step 1.8565139611562094: Fetching target URL
9RPK-XAAH step 1.8789840592278375: Fetching target URL
9RPK-XAAH step 1.9014645576477052: Fetching target URL
9RPK-XAAH step 1.9239173465304904: Fetching target URL
9RPK-XAAH step 1.9464031643337674: Fetching target URL
9RPK-XAAH step 1.9688877529568143: Fetching target URL
9RPK-XAAH step 1.9912626372443305: Fetching target URL
HaltCaptureException thrown
Shutting down browser and proxies.
4 active threads.
Waiting for MitmProxyHandler
4 active threads.
Waiting for MitmProxyHandler
4 active threads.
Waiting for MitmProxyHandler
4 active threads.
Waiting for MitmProxyHandler
4 active threads.
Waiting for MitmProxyHandler
4 active threads.
Waiting for MitmProxyHandler
4 active threads.
Waiting for MitmProxyHandler
4 active threads.
Waiting for MitmProxyHandler
4 active threads.
Waiting for MitmProxyHandler
4 active threads.
Waiting for MitmProxyHandler
4 active threads.
Waiting for MitmProxyHandler
9RPK-XAAH capture failed.
[27/Mar/2019 14:49:12] "POST /api/v1/archives/ HTTP/1.1" 201 981
[27/Mar/2019 14:49:12] "GET /api/v1/user/capture_jobs/9RPK-XAAH HTTP/1.1" 200 397
WarcProx exception: timeout proxying https://taxpayeradvocate.irs.gov/
```

**Comment by rebeccacremona** [comment]
Warcprox's `WarcProxyHandler._proxy_request` never returns.

**Comment by rebeccacremona** [comment]
Upgrading to `warcprox==2.4b6` does not help.

**Comment by rebeccacremona** [comment]
Aha! Deep in the Django logs, from warcprox,
```
2019-03-27 16:32:48,041 [WARNING] connectionpool.py 400: Failed to parse headers (url=https://taxpayeradvocate.irs.gov:443/): [MissingHeaderBodySeparatorDefect()], unparsed data: 'Server Name: IAD-WEB-WEBER\r\nX-Powered-By: ASP.NET\r\nX-Secure: True\r\nStrict-Transport-Security: max-age=10886400\r\nDate: Wed, 27 Mar 2019 16:32:46 GMT\r\nContent-Length: 5549\r\n\r\n'
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/perma_web-kkDLCj8f/lib/python3.5/site-packages/urllib3/connectionpool.py", line 396, in _make_request
    assert_header_parsing(httplib_response.msg)
  File "/root/.local/share/virtualenvs/perma_web-kkDLCj8f/lib/python3.5/site-packages/urllib3/util/response.py", line 72, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: 'Server Name: IAD-WEB-WEBER\r\nX-Powered-By: ASP.NET\r\nX-Secure: True\r\nStrict-Transport-Security: max-age=10886400\r\nDate: Wed, 27 Mar 2019 16:32:46 GMT\r\nContent-Length: 5549\r\n\r\n'
```

**Comment by rebeccacremona** [comment]
`unparsed data: 'Server Name:` there's a space there.... "Server Name" is an illegal header. I observe that Firefox drops all mention of that header in the dev tools. Curl includes it, but doesn't complain....
```
MSC02VK05ZHTDG:perma rcremona$ curl -i https://taxpayeradvocate.irs.gov/
HTTP/1.1 200 OK
Cache-Control: private
Content-Type: text/html; charset=utf-8
Server: Microsoft-IIS/7.5
X-Generator: Orchard
X-AspNetMvc-Version: 5.2
X-AspNet-Version: 4.0.30319
Server Name: IAD-WEB-WEBER
X-Powered-By: ASP.NET
X-Secure: True
Strict-Transport-Security: max-age=10886400
Date: Wed, 27 Mar 2019 16:56:45 GMT
Content-Length: 16257
```

**Comment by rebeccacremona** [comment]
`urllib3` maintainers say,
>Historically there have been many security issues with accepting HTTP headers that have spaces in non-standard places so I think us parsing headers to spec is the proper thing to do. To allow this we'd have to replace httplib which is something a ways off for this project (I'll note the current candidate for replacing httplib is h11 which would also error on this header).
>
> Unfortunately I'd say your best course of action is to contact the website owners. Sorry!"
https://github.com/urllib3/urllib3/issues/1433

I wonder how to open a ticket with the IRS 😬

**Comment by rebeccacremona** [comment]
Hmm, though not clear to me why this is fatal in our case...... https://github.com/urllib3/urllib3/blob/46331f94275a4c3b4c71a358a495b1caeaececa0/src/urllib3/connectionpool.py#L404. Maybe I spoke to soon... is the problem actually the absence of headers +  https://github.com/harvard-lil/perma/blob/develop/perma_web/perma/tasks.py#L1096?

**Comment by rebeccacremona** [comment]
Nope, it's not us, we never get to the above line: as I said, WarcProxyHandler._proxy_request never returns, and it's not due to https://github.com/harvard-lil/perma/blob/develop/perma_web/perma/tasks.py#L144.... I can print `self.recorder.headers` right there in the patch, and get the expected:
```
Cache-Control: private
Content-Type: text/html; charset=utf-8
Server: Microsoft-IIS/7.5
X-Generator: Orchard
X-AspNetMvc-Version: 5.2
X-AspNet-Version: 4.0.30319
Via: 1.1 warcprox

Server Name: IAD-WEB-WEBER
X-Powered-By: ASP.NET
X-Secure: True
Strict-Transport-Security: max-age=10886400
Date: Wed, 27 Mar 2019 17:21:30 GMT
Content-Length: 16257
```

**Comment by rebeccacremona** [comment]
The `read` is sticking... https://github.com/internetarchive/warcprox/blob/2.4b2/warcprox/mitmproxy.py#L465. Verified by commenting out the first read, and observing that we then stick at the next read, in the `while`....

**Comment by rebeccacremona** [comment]
We're sticking here: https://github.com/internetarchive/warcprox/blob/2.4b2/warcprox/mitmproxy.py#L192

**Comment by rebeccacremona** [comment]
Which is https://github.com/python/cpython/blob/3.5/Lib/http/client.py#L437

**Comment by rebeccacremona** [comment]
Which itself sticks here: https://github.com/python/cpython/blob/3.5/Lib/http/client.py#L448

**Comment by rebeccacremona** [comment]
Which itself sticks here: https://github.com/python/cpython/blob/3.5/Lib/http/client.py#L488

**Comment by rebeccacremona** [comment]
Hmm, I wonder if this is why....
```
        # If the response includes a content-length header, we need to
        # make sure that the client doesn't read more than the
        # specified number of bytes.  If it does, it will block until
        # the server times out and closes the connection.  This will
        # happen if a self.fp.read() is done (without a size) whether
        # self.fp is buffered or not.  So, no self.fp.read() by
        # clients unless they know what they are doing.
        self.fp = sock.makefile("rb")
```

**Comment by rebeccacremona** [comment]
Okay, this is beyond me... I think stuck in this loop, but dunno why https://github.com/python/cpython/blob/3.5/Lib/socket.py#L574

**Comment by rebeccacremona** [comment]
I think because the header parser is failing, `self.length` is incorrectly None (https://github.com/python/cpython/blob/3.5/Lib/http/client.py#L341) and therefore `self.fp.read()` is getting called instead of `self._safe_read(self.length)` (https://github.com/python/cpython/blob/3.5/Lib/http/client.py#L457), and so we're blocking as per the message above.

**Comment by rebeccacremona** [comment]
No idea how me might work around this. Obviously browsers do, but....

**Comment by rebeccacremona** [comment]
Does not work in production WebRecorder either.

**Comment by rebeccacremona** [comment]
They have since removed that header...... I'm going to mark this an unsolved mystery.
