### ISSUE TITLE
wr session error related to expiration time

### ISSUE THREAD

**Issue by rebeccacremona** [harvard-lil/perma#2601]
This line https://github.com/webrecorder/webrecorder/blob/master/webrecorder/webrecorder/session.py#L399 evidently tried to set an expiration of 0. It appears to use https://github.com/webrecorder/webrecorder/blob/master/webrecorder/webrecorder/session.py#L382 to get a duration.....

We configure that [here](https://github.com/harvard-lil/perma/blob/develop/services/docker/webrecorder/wr-custom.yaml), no zeroes for "total".... [nor in WR's own](https://github.com/webrecorder/webrecorder/blame/master/webrecorder/webrecorder/config/wr.yaml).... 

So what happened here? How did it get a zero? (And is zero invalid?)

If this happens regularly, let's dig in. Or change "extend" to non-zero values.

```
  May 30 15:21:31 ip-172-31-48-6 docker-compose[644]: warcserver_1  | [pid: 17|app: 0|req: 1014/5401] 172.18.0.4 () {32 vars in 889 bytes} [Thu May 30 15:21:31 2019] POST /replay-coll/resource/postreq?param.user=public&param.coll=3ynwdhic5q6ayv3i&param.rec=*&url=http%3A%2F%2Fanalytics.firespring.com%2Fin.php%3Fsite_id%3D100990792%26type%3Dping%26mime%3Djs%26x%3D0.26609224965706446&closest=20190530151509&matchType=exact => generated 32 bytes in 2 msecs (HTTP/1.1 404) 3 headers in 146 bytes (3 switches on core 398)
    May 30 15:21:32 ip-172-31-48-6 docker-compose[644]: app_1         | Traceback (most recent call last):
    May 30 15:21:32 ip-172-31-48-6 docker-compose[644]: app_1         |   File "/usr/local/lib/python3.7/site-packages/bottle.py", line 960, in wsgi
    May 30 15:21:32 ip-172-31-48-6 docker-compose[644]: app_1         |     start_response(response._status_line, response.headerlist)
    May 30 15:21:32 ip-172-31-48-6 docker-compose[644]: app_1         |   File "./webrecorder/cookieguard.py", line 14, in guard_start_response
    May 30 15:21:32 ip-172-31-48-6 docker-compose[644]: app_1         |     self.prepare_response(environ, headers)
    May 30 15:21:32 ip-172-31-48-6 docker-compose[644]: app_1         |   File "./webrecorder/session.py", line 357, in prepare_response
    May 30 15:21:32 ip-172-31-48-6 docker-compose[644]: app_1         |     self._update_redis_and_cookie(set_cookie, session, headers)
    May 30 15:21:32 ip-172-31-48-6 docker-compose[644]: app_1         |   File "./webrecorder/session.py", line 399, in _update_redis_and_cookie
    May 30 15:21:32 ip-172-31-48-6 docker-compose[644]: app_1         |     pi.expire(session.key, duration)
    May 30 15:21:32 ip-172-31-48-6 docker-compose[644]: app_1         |   File "/usr/local/lib/python3.7/contextlib.py", line 119, in __exit__
    May 30 15:21:32 ip-172-31-48-6 docker-compose[644]: app_1         |     next(self.gen)
    May 30 15:21:32 ip-172-31-48-6 docker-compose[644]: app_1         |   File "./webrecorder/utils.py", line 127, in redis_pipeline
    May 30 15:21:32 ip-172-31-48-6 docker-compose[644]: app_1         |     p.execute()
    May 30 15:21:32 ip-172-31-48-6 docker-compose[644]: app_1         |   File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 2879, in execute
    May 30 15:21:32 ip-172-31-48-6 docker-compose[644]: app_1         |     return execute(conn, stack, raise_on_error)
    May 30 15:21:32 ip-172-31-48-6 docker-compose[644]: app_1         |   File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 2821, in _execute_pipeline
    May 30 15:21:32 ip-172-31-48-6 docker-compose[644]: app_1         |     self.raise_first_error(commands, response)
    May 30 15:21:32 ip-172-31-48-6 docker-compose[644]: app_1         |   File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 2828, in raise_first_error
    May 30 15:21:32 ip-172-31-48-6 docker-compose[644]: app_1         |     raise r
    May 30 15:21:32 ip-172-31-48-6 docker-compose[644]: app_1         |   File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 2816, in _execute_pipeline
    May 30 15:21:32 ip-172-31-48-6 docker-compose[644]: app_1         |     self.parse_response(connection, args[0], **options))
    May 30 15:21:32 ip-172-31-48-6 docker-compose[644]: app_1         |   File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 2838, in parse_response
    May 30 15:21:32 ip-172-31-48-6 docker-compose[644]: app_1         |     self, connection, command_name, **options)
    May 30 15:21:32 ip-172-31-48-6 docker-compose[644]: app_1         |   File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 680, in parse_response
    May 30 15:21:32 ip-172-31-48-6 docker-compose[644]: app_1         |     response = connection.read_response()
    May 30 15:21:32 ip-172-31-48-6 docker-compose[644]: app_1         |   File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 629, in read_response
    May 30 15:21:32 ip-172-31-48-6 docker-compose[644]: app_1         |     raise response
    May 30 15:21:32 ip-172-31-48-6 docker-compose[644]: app_1         | redis.exceptions.ResponseError: Command # 1 (SETEX sesh:lZCkrvY9Ud24FEIYkBjn3E9n6xY= 0 b'gAN9cQBYAgAAAGlkcQFYHAAAAGxaQ2tydlk5VWQyNEZFSVlrQmpuM0U5bjZ4WT1xAnMu') of pipeline caused error: invalid expire time in setex
    May 30 15:21:32 ip-172-31-48-6 docker-compose[644]: app_1         |
    May 30 15:21:32 ip-172-31-48-6 docker-compose[644]: app_1         | During handling of the above exception, another exception occurred:
    May 30 15:21:32 ip-172-31-48-6 docker-compose[644]: app_1         |
    May 30 15:21:32 ip-172-31-48-6 docker-compose[644]: app_1         | Traceback (most recent call last):
    May 30 15:21:32 ip-172-31-48-6 docker-compose[644]: app_1         |   File "/usr/local/lib/python3.7/site-packages/wsgiprox/wsgiprox.py", line 428, in __call__
    May 30 15:21:32 ip-172-31-48-6 docker-compose[644]: app_1         |     return self.wsgi(env, start_response)
    May 30 15:21:32 ip-172-31-48-6 docker-compose[644]: app_1         |   File "/usr/local/lib/python3.7/site-packages/wsgiprox/wsgiprox.py", line 417, in wsgi
    May 30 15:21:32 ip-172-31-48-6 docker-compose[644]: app_1         |     return self._wsgi(env, start_response)
    May 30 15:21:32 ip-172-31-48-6 docker-compose[644]: app_1         |   File "./webrecorder/cookieguard.py", line 18, in __call__
    May 30 15:21:32 ip-172-31-48-6 docker-compose[644]: app_1         |     return self.app(environ, guard_start_response)
    May 30 15:21:32 ip-172-31-48-6 docker-compose[644]: app_1         |   File "/usr/local/lib/python3.7/site-packages/bottle.py", line 979, in __call__
    May 30 15:21:32 ip-172-31-48-6 docker-compose[644]: app_1         |     return self.wsgi(environ, start_response)
    May 30 15:21:32 ip-172-31-48-6 docker-compose[644]: app_1         |   File "/usr/local/lib/python3.7/site-packages/bottle.py", line 974, in wsgi
    May 30 15:21:32 ip-172-31-48-6 docker-compose[644]: app_1         |     start_response('500 INTERNAL SERVER ERROR', headers, sys.exc_info())
    May 30 15:21:32 ip-172-31-48-6 docker-compose[644]: app_1         |   File "./webrecorder/cookieguard.py", line 14, in guard_start_response
    May 30 15:21:32 ip-172-31-48-6 docker-compose[644]: app_1         |     self.prepare_response(environ, headers)
    May 30 15:21:32 ip-172-31-48-6 docker-compose[644]: app_1         |   File "./webrecorder/session.py", line 357, in prepare_response
    May 30 15:21:32 ip-172-31-48-6 docker-compose[644]: app_1         |     self._update_redis_and_cookie(set_cookie, session, headers)
    May 30 15:21:32 ip-172-31-48-6 docker-compose[644]: app_1         |   File "./webrecorder/session.py", line 399, in _update_redis_and_cookie
    May 30 15:21:32 ip-172-31-48-6 docker-compose[644]: app_1         |     pi.expire(session.key, duration)
    May 30 15:21:32 ip-172-31-48-6 docker-compose[644]: app_1         |   File "/usr/local/lib/python3.7/contextlib.py", line 119, in __exit__
    May 30 15:21:32 ip-172-31-48-6 docker-compose[644]: app_1         |     next(self.gen)
    May 30 15:21:32 ip-172-31-48-6 docker-compose[644]: app_1         |   File "./webrecorder/utils.py", line 127, in redis_pipeline
    May 30 15:21:32 ip-172-31-48-6 docker-compose[644]: app_1         |     p.execute()
    May 30 15:21:32 ip-172-31-48-6 docker-compose[644]: app_1         |   File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 2879, in execute
    May 30 15:21:32 ip-172-31-48-6 docker-compose[644]: app_1         |     return execute(conn, stack, raise_on_error)
    May 30 15:21:32 ip-172-31-48-6 docker-compose[644]: app_1         |   File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 2821, in _execute_pipeline
    May 30 15:21:32 ip-172-31-48-6 docker-compose[644]: app_1         |     self.raise_first_error(commands, response)
    May 30 15:21:32 ip-172-31-48-6 docker-compose[644]: app_1         |   File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 2828, in raise_first_error
    May 30 15:21:32 ip-172-31-48-6 docker-compose[644]: app_1         |     raise r
    May 30 15:21:32 ip-172-31-48-6 docker-compose[644]: app_1         |   File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 2816, in _execute_pipeline
    May 30 15:21:32 ip-172-31-48-6 docker-compose[644]: app_1         |     self.parse_response(connection, args[0], **options))
    May 30 15:21:32 ip-172-31-48-6 docker-compose[644]: app_1         |   File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 2838, in parse_response
    May 30 15:21:32 ip-172-31-48-6 docker-compose[644]: app_1         |     self, connection, command_name, **options)
    May 30 15:21:32 ip-172-31-48-6 docker-compose[644]: app_1         |   File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 680, in parse_response
    May 30 15:21:32 ip-172-31-48-6 docker-compose[644]: app_1         |     response = connection.read_response()
    May 30 15:21:32 ip-172-31-48-6 docker-compose[644]: app_1         |   File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 629, in read_response
    May 30 15:21:32 ip-172-31-48-6 docker-compose[644]: app_1         |     raise response
    May 30 15:21:32 ip-172-31-48-6 docker-compose[644]: app_1         | redis.exceptions.ResponseError: Command # 1 (SETEX sesh:lZCkrvY9Ud24FEIYkBjn3E9n6xY= 0 b'gAN9cQBYAgAAAGlkcQFYHAAAAGxaQ2tydlk5VWQyNEZFSVlrQmpuM0U5bjZ4WT1xAnMu') of pipeline caused error: invalid expire time in setex
    May 30 15:21:32 ip-172-31-48-6 docker-compose[644]: nginx_1       | 2019/05/30 15:21:32 [error] 6#6: *506021 upstream prematurely closed connection while reading response header from upstream, client: 172.69.6.24, server: wr-prod-004.perma-archives.org, request: "POST /public/7zy8-26r2/20190530151509mp_///analytics.firespring.com/in.php?site_id=100990792&type=ping&mime=js&x=0.26609224965706446 HTTP/1.1", upstream: "uwsgi://172.18.0.4:8081", host: "wr.perma-archives.org", referrer: "https://wr.perma-archives.org/public/7zy8-26r2/20190530151507mp_/https://thebluebench.org/learn/common-misconceptions.html"
```

**Comment by rebeccacremona** [comment]
Confirmed that SETEX expects a positive value for expiration (0 is indeed invalid). Still investigating where the 0 is coming from.

**Comment by rebeccacremona** [comment]
So, this part of the session-handling code uses a custom ["redis pipeline" context manager](https://github.com/webrecorder/webrecorder/blob/master/webrecorder/webrecorder/utils.py#L124). The way it works, the redis commands applied to "p" will execute in order as the context is being exited; the last line of [this stanza](https://github.com/webrecorder/webrecorder/blob/master/webrecorder/webrecorder/session.py#L385-L399). That's why we're seeing this exception being thrown, seemingly, at `File "./webrecorder/session.py", line 399... pi.expire(session.key, duration)`, when it's really `392... pi.setex(session.key, ttl, data)` that's the problem.

That's also why putting narrow try/excepts inside the context of the `with` didn't work: the exception is being thrown in `__exit__()`, so if you want to catch it, you have to wrap the whole context with try/except.

**Comment by rebeccacremona** [comment]
I think we've got this one. I'll send a PR upstream shortly.
