### ISSUE TITLE
mime key error

### ISSUE THREAD

**Issue by rebeccacremona** [harvard-lil/perma#2602]
Have not yet been able to reproduce this, locally or on prod

```
GET /api/v1/up
load/HG5AS6JT?user=public => generated 209 bytes in 11 msecs (HTTP/1.1 200) 2 headers in 72 bytes (3 switches on core 399)
    May 30 16:23:43 ip-172-31-48-6 docker-compose[644]: app_1         | Traceback (most recent call last):
    May 30 16:23:43 ip-172-31-48-6 docker-compose[644]: app_1         |   File "./webrecorder/models/importer.py", line 244, in run_upload
    May 30 16:23:43 ip-172-31-48-6 docker-compose[644]: app_1         |     self.process_pages(info, page_id_map)
    May 30 16:23:43 ip-172-31-48-6 docker-compose[644]: app_1         |   File "./webrecorder/models/importer.py", line 289, in process_pages
    May 30 16:23:43 ip-172-31-48-6 docker-compose[644]: app_1         |     pages = self.detect_pages(info['coll'], info['rec'])
    May 30 16:23:43 ip-172-31-48-6 docker-compose[644]: app_1         |   File "./webrecorder/models/importer.py", line 458, in detect_pages
    May 30 16:23:43 ip-172-31-48-6 docker-compose[644]: app_1         |     and self.is_page(cdxj)):
    May 30 16:23:43 ip-172-31-48-6 docker-compose[644]: app_1         |   File "./webrecorder/models/importer.py", line 481, in is_page
    May 30 16:23:43 ip-172-31-48-6 docker-compose[644]: app_1         |     if (cdxj['mime'] in ('text/html', 'text/plain')  and
    May 30 16:23:43 ip-172-31-48-6 docker-compose[644]: app_1         | KeyError: 'mime'
    May 30 16:23:43 ip-172-31-48-6 docker-compose[644]: app_1         | [pid: 10|app: 0|req: 60296/266920] 172.69.240.50 () {36 vars in 553 bytes} [Thu May 30 16:23:43 2019] GET /api/v1 => generated 36088 bytes in 122 msecs (HTTP/1.1 200) 2 headers in 67 bytes (3 switches on core 397)
```

**Comment by rebeccacremona** [comment]
This almost certainly was due to a mis-parsed CDXLine, caused by a space in the url, ala https://github.com/harvard-lil/perma/issues/2605. I'm going to close for now. We can re-open if we notice more of these.

**Comment by rebeccacremona** [comment]
Happened again:
