### ISSUE TITLE
evidently a bad header

### ISSUE THREAD

**Issue by rebeccacremona** [harvard-lil/perma#2603]
Though visiting 3p55-t6bb does not now seem to produce the same error, in prod or locally... looks fine.....

```
May 30 19:51:31 ip-172-31-60-73 docker-compose[651]: app_1         |     return start_response(status, headers, exc_info)
May 30 19:51:31 ip-172-31-60-73 docker-compose[651]: app_1         | TypeError: http header must be encodable in latin1
May 30 19:51:31 ip-172-31-60-73 docker-compose[651]: app_1         |
May 30 19:51:31 ip-172-31-60-73 docker-compose[651]: app_1         | The above exception was the direct cause of the following exception:
May 30 19:51:31 ip-172-31-60-73 docker-compose[651]: app_1         |
May 30 19:51:31 ip-172-31-60-73 docker-compose[651]: app_1         | Traceback (most recent call last):
May 30 19:51:31 ip-172-31-60-73 docker-compose[651]: app_1         |   File "/usr/local/lib/python3.7/site-packages/wsgiprox/wsgiprox.py", line 428, in __call__
May 30 19:51:31 ip-172-31-60-73 docker-compose[651]: app_1         |     return self.wsgi(env, start_response)
May 30 19:51:31 ip-172-31-60-73 docker-compose[651]: app_1         |   File "/usr/local/lib/python3.7/site-packages/wsgiprox/wsgiprox.py", line 417, in wsgi
May 30 19:51:31 ip-172-31-60-73 docker-compose[651]: app_1         |     return self._wsgi(env, start_response)
May 30 19:51:31 ip-172-31-60-73 docker-compose[651]: app_1         |   File "./webrecorder/cookieguard.py", line 18, in __call__
May 30 19:51:31 ip-172-31-60-73 docker-compose[651]: app_1         |     return self.app(environ, guard_start_response)
May 30 19:51:31 ip-172-31-60-73 docker-compose[651]: app_1         |   File "/usr/local/lib/python3.7/site-packages/bottle.py", line 979, in __call__
May 30 19:51:31 ip-172-31-60-73 docker-compose[651]: app_1         |     return self.wsgi(environ, start_response)
May 30 19:51:31 ip-172-31-60-73 docker-compose[651]: app_1         |   File "/usr/local/lib/python3.7/site-packages/bottle.py", line 974, in wsgi
May 30 19:51:31 ip-172-31-60-73 docker-compose[651]: app_1         |     start_response('500 INTERNAL SERVER ERROR', headers, sys.exc_info())
May 30 19:51:31 ip-172-31-60-73 docker-compose[651]: app_1         |   File "./webrecorder/cookieguard.py", line 16, in guard_start_response
May 30 19:51:31 ip-172-31-60-73 docker-compose[651]: app_1         |     return start_response(status, headers, exc_info)
May 30 19:51:31 ip-172-31-60-73 docker-compose[651]: app_1         | SystemError: <built-in function uwsgi_spit> returned a result with an error set
May 30 19:51:31 ip-172-31-60-73 docker-compose[651]: nginx_1       | 172.68.47.222 - - [30/May/2019:19:51:31 +0000] "GET /public/3p55-t6bb/20190530195126mp_/https://www.garrettparkmd.gov/home/showdocument?id=669 HTTP/1.1" 500 5 "https://perma.cc/3P55-T6BB" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36"
May 30 19:51:31 ip-172-31-60-73 docker-compose[651]: app_1         | [pid: 18|app: 0|req: 29832/308342] 206.211.146.61 () {62 vars in 1445 bytes} [Thu May 30 19:51:31 2019] GET /public/3p55-t6bb/20190530195126mp_/https://www.garrettparkmd.gov/home/showdocument?id=669 => generated 0 bytes in 42 msecs (HTTP/1.1 500) 2 headers in 214 bytes (1 switches on core 398)
May 30 19:51:31 ip-172-31-60-73 docker-compose[651]: nginx_1       | 172.68.120.135 - - [30/May/2019:19:51:31 +0000] "GET /api/v1 HTTP/1.1" 200 36088 "-" "Mozilla/5.0 (compatible; Cloudflare-Traffic-Manager/1.0; +https://www.cloudflare.com/traffic-manager/; pool-id: 857383f5bcfc41d0)"
May 30 19:51:31 ip-172-31-60-73 docker-compose[651]: app_1         | [pid: 16|app: 0|req: 41393/308343] 172.68.120.135 () {36 vars in 554 bytes} [Thu May 30 19:51:31 2019] GET /api/v1 => generated 36088 bytes in 157 msecs (HTTP/1.1 200) 2 headers in 67 bytes (3 switches on core 392)
May 30 19:51:31 ip-172-31-60-73 docker-compose[651]: nginx_1       | 172.69.197.4 - - [30/May/2019:19:51:31 +0000] "GET /api/v1 HTTP/1.1" 200 36088 "-" "Mozilla/5.0 (compatible; Cloudflare-Traffic-Manager/1.0; +https://www.cloudflare.com/traffic-manager/; pool-id: 857383f5bcfc41d0)"
May 30 19:51:31 ip-172-31-60-73 docker-compose[651]: app_1         | [pid: 10|app: 0|req: 105504/308344] 172.69.197.4 () {36 vars in 552 bytes} [Thu May 30 19:51:31 2019] GET /api/v1 => generated 36088 bytes in 186 msecs (HTTP/1.1 200) 2 headers in 67 bytes (3 switches on core 394)
May 30 19:51:32 ip-172-31-60-73 docker-compose[651]: app_1         | [pid: 17|app: 0|req: 24532/308345] 172.69.60.167 () {36 vars in 553 bytes} [Thu May 30 19:51:31 2019] GET /api/v1 => generated 36088 bytes in 126 msecs (HTTP/1.1 200) 2 headers in 67 bytes (3 switches on core 398)
tac: write error: Broken pipe
```

**Comment by rebeccacremona** [comment]
Possibly the same?
```
    Jun 24 18:22:30 ip-172-31-58-70 docker-compose[25954]: app_1         | Traceback (most recent call last):
    Jun 24 18:22:30 ip-172-31-58-70 docker-compose[25954]: app_1         |   File "/usr/local/lib/python3.7/site-packages/bottle.py", line 960, in wsgi
    Jun 24 18:22:30 ip-172-31-58-70 docker-compose[25954]: app_1         |     start_response(response._status_line, response.headerlist)
    Jun 24 18:22:30 ip-172-31-58-70 docker-compose[25954]: app_1         |   File "./webrecorder/cookieguard.py", line 16, in guard_start_response
    Jun 24 18:22:30 ip-172-31-58-70 docker-compose[25954]: app_1         |     return start_response(status, headers, exc_info)
    Jun 24 18:22:30 ip-172-31-58-70 docker-compose[25954]: app_1         | TypeError: unable to add header to the response
    Jun 24 18:22:30 ip-172-31-58-70 docker-compose[25954]: app_1         |
    Jun 24 18:22:30 ip-172-31-58-70 docker-compose[25954]: app_1         | The above exception was the direct cause of the following exception:
    Jun 24 18:22:30 ip-172-31-58-70 docker-compose[25954]: app_1         |
    Jun 24 18:22:30 ip-172-31-58-70 docker-compose[25954]: app_1         | Traceback (most recent call last):
    Jun 24 18:22:30 ip-172-31-58-70 docker-compose[25954]: app_1         |   File "/usr/local/lib/python3.7/site-packages/wsgiprox/wsgiprox.py", line 428, in __call__
    Jun 24 18:22:30 ip-172-31-58-70 docker-compose[25954]: app_1         |     return self.wsgi(env, start_response)
    Jun 24 18:22:30 ip-172-31-58-70 docker-compose[25954]: app_1         |   File "/usr/local/lib/python3.7/site-packages/wsgiprox/wsgiprox.py", line 417, in wsgi
    Jun 24 18:22:30 ip-172-31-58-70 docker-compose[25954]: app_1         |     return self._wsgi(env, start_response)
    Jun 24 18:22:30 ip-172-31-58-70 docker-compose[25954]: app_1         |   File "./webrecorder/cookieguard.py", line 18, in __call__
    Jun 24 18:22:30 ip-172-31-58-70 docker-compose[25954]: app_1         |     return self.app(environ, guard_start_response)
    Jun 24 18:22:30 ip-172-31-58-70 docker-compose[25954]: app_1         |   File "/usr/local/lib/python3.7/site-packages/bottle.py", line 979, in __call__
    Jun 24 18:22:30 ip-172-31-58-70 docker-compose[25954]: app_1         |     return self.wsgi(environ, start_response)
    Jun 24 18:22:30 ip-172-31-58-70 docker-compose[25954]: app_1         |   File "/usr/local/lib/python3.7/site-packages/bottle.py", line 974, in wsgi
    Jun 24 18:22:30 ip-172-31-58-70 docker-compose[25954]: app_1         |     start_response('500 INTERNAL SERVER ERROR', headers, sys.exc_info())
    Jun 24 18:22:30 ip-172-31-58-70 docker-compose[25954]: app_1         |   File "./webrecorder/cookieguard.py", line 16, in guard_start_response
    Jun 24 18:22:30 ip-172-31-58-70 docker-compose[25954]: app_1         |     return start_response(status, headers, exc_info)
    Jun 24 18:22:30 ip-172-31-58-70 docker-compose[25954]: app_1         | SystemError: <built-in function uwsgi_spit> returned a result with an error set
    Jun 24 18:22:30 ip-172-31-58-70 docker-compose[25954]: app_1         | Traceback (most recent call last):
    Jun 24 18:22:30 ip-172-31-58-70 docker-compose[25954]: app_1         |   File "/usr/local/lib/python3.7/site-packages/bottle.py", line 960, in wsgi
    Jun 24 18:22:30 ip-172-31-58-70 docker-compose[25954]: app_1         |     start_response(response._status_line, response.headerlist)
    Jun 24 18:22:30 ip-172-31-58-70 docker-compose[25954]: app_1         |   File "./webrecorder/cookieguard.py", line 16, in guard_start_response
    Jun 24 18:22:30 ip-172-31-58-70 docker-compose[25954]: app_1         |     return start_response(status, headers, exc_info)
    Jun 24 18:22:30 ip-172-31-58-70 docker-compose[25954]: app_1         | TypeError: unable to add header to the response
    Jun 24 18:22:30 ip-172-31-58-70 docker-compose[25954]: app_1         |
    Jun 24 18:22:30 ip-172-31-58-70 docker-compose[25954]: app_1         | The above exception was the direct cause of the following exception:
    Jun 24 18:22:30 ip-172-31-58-70 docker-compose[25954]: app_1         |
    Jun 24 18:22:30 ip-172-31-58-70 docker-compose[25954]: app_1         | Traceback (most recent call last):
    Jun 24 18:22:30 ip-172-31-58-70 docker-compose[25954]: app_1         |   File "/usr/local/lib/python3.7/site-packages/wsgiprox/wsgiprox.py", line 428, in __call__
    Jun 24 18:22:30 ip-172-31-58-70 docker-compose[25954]: app_1         |     return self.wsgi(env, start_response)
    Jun 24 18:22:30 ip-172-31-58-70 docker-compose[25954]: app_1         |   File "/usr/local/lib/python3.7/site-packages/wsgiprox/wsgiprox.py", line 417, in wsgi
    Jun 24 18:22:30 ip-172-31-58-70 docker-compose[25954]: app_1         |     return self._wsgi(env, start_response)
    Jun 24 18:22:30 ip-172-31-58-70 docker-compose[25954]: app_1         |   File "./webrecorder/cookieguard.py", line 18, in __call__
    Jun 24 18:22:30 ip-172-31-58-70 docker-compose[25954]: app_1         |     return self.app(environ, guard_start_response)
    Jun 24 18:22:30 ip-172-31-58-70 docker-compose[25954]: app_1         |   File "/usr/local/lib/python3.7/site-packages/bottle.py", line 979, in __call__
    Jun 24 18:22:30 ip-172-31-58-70 docker-compose[25954]: app_1         |     return self.wsgi(environ, start_response)
    Jun 24 18:22:30 ip-172-31-58-70 docker-compose[25954]: app_1         |   File "/usr/local/lib/python3.7/site-packages/bottle.py", line 974, in wsgi
    Jun 24 18:22:30 ip-172-31-58-70 docker-compose[25954]: app_1         |     start_response('500 INTERNAL SERVER ERROR', headers, sys.exc_info())
    Jun 24 18:22:30 ip-172-31-58-70 docker-compose[25954]: app_1         |   File "./webrecorder/cookieguard.py", line 16, in guard_start_response
    Jun 24 18:22:30 ip-172-31-58-70 docker-compose[25954]: app_1         |     return start_response(status, headers, exc_info)
    Jun 24 18:22:30 ip-172-31-58-70 docker-compose[25954]: app_1         | SystemError: <built-in function uwsgi_spit> returned a result with an error set
    Jun 24 18:22:31 ip-172-31-58-70 docker-compose[25954]: app_1         | Traceback (most recent call last):
    Jun 24 18:22:31 ip-172-31-58-70 docker-compose[25954]: app_1         |   File "/usr/local/lib/python3.7/site-packages/bottle.py", line 960, in wsgi
    Jun 24 18:22:31 ip-172-31-58-70 docker-compose[25954]: app_1         |     start_response(response._status_line, response.headerlist)
    Jun 24 18:22:31 ip-172-31-58-70 docker-compose[25954]: app_1         |   File "./webrecorder/cookieguard.py", line 16, in guard_start_response
    Jun 24 18:22:31 ip-172-31-58-70 docker-compose[25954]: app_1         |     return start_response(status, headers, exc_info)
    Jun 24 18:22:31 ip-172-31-58-70 docker-compose[25954]: app_1         | TypeError: unable to add header to the response
    Jun 24 18:22:31 ip-172-31-58-70 docker-compose[25954]: app_1         |
    Jun 24 18:22:31 ip-172-31-58-70 docker-compose[25954]: app_1         | The above exception was the direct cause of the following exception:
    Jun 24 18:22:31 ip-172-31-58-70 docker-compose[25954]: app_1         |
    Jun 24 18:22:31 ip-172-31-58-70 docker-compose[25954]: app_1         | Traceback (most recent call last):
    Jun 24 18:22:31 ip-172-31-58-70 docker-compose[25954]: app_1         |   File "/usr/local/lib/python3.7/site-packages/wsgiprox/wsgiprox.py", line 428, in __call__
    Jun 24 18:22:31 ip-172-31-58-70 docker-compose[25954]: app_1         |     return self.wsgi(env, start_response)
    Jun 24 18:22:31 ip-172-31-58-70 docker-compose[25954]: app_1         |   File "/usr/local/lib/python3.7/site-packages/wsgiprox/wsgiprox.py", line 417, in wsgi
    Jun 24 18:22:31 ip-172-31-58-70 docker-compose[25954]: app_1         |     return self._wsgi(env, start_response)
    Jun 24 18:22:31 ip-172-31-58-70 docker-compose[25954]: app_1         |   File "./webrecorder/cookieguard.py", line 18, in __call__
    Jun 24 18:22:31 ip-172-31-58-70 docker-compose[25954]: app_1         |     return self.app(environ, guard_start_response)
    Jun 24 18:22:31 ip-172-31-58-70 docker-compose[25954]: app_1         |   File "/usr/local/lib/python3.7/site-packages/bottle.py", line 979, in __call__
    Jun 24 18:22:31 ip-172-31-58-70 docker-compose[25954]: app_1         |     return self.wsgi(environ, start_response)
    Jun 24 18:22:31 ip-172-31-58-70 docker-compose[25954]: app_1         |   File "/usr/local/lib/python3.7/site-packages/bottle.py", line 974, in wsgi
    Jun 24 18:22:31 ip-172-31-58-70 docker-compose[25954]: app_1         |     start_response('500 INTERNAL SERVER ERROR', headers, sys.exc_info())
    Jun 24 18:22:31 ip-172-31-58-70 docker-compose[25954]: app_1         |   File "./webrecorder/cookieguard.py", line 16, in guard_start_response
    Jun 24 18:22:31 ip-172-31-58-70 docker-compose[25954]: app_1         |     return start_response(status, headers, exc_info)
    Jun 24 18:22:31 ip-172-31-58-70 docker-compose[25954]: app_1         | SystemError: <built-in function uwsgi_spit> returned a result with an error set
```

**Comment by rebeccacremona** [comment]
We're in here, evidently.... https://github.com/unbit/uwsgi/blob/master/plugins/python/wsgi_headers.c

**Comment by rebeccacremona** [comment]
A user reported a broken link, that turns out to be producing this error: https://perma.cc/9LDH-X4VF

Clever sleuthing by Ben revealed it is due to Hebrew characters in the content disposition header. From the original site:
```
Content-Disposition: inline; filename="חוק הטיס 1927 חוק הטיס - ינואר 2016.pdf"; filename*=UTF-8''%D7%97%D7%95%D7%A7%20%D7%94%D7%98%D7%99%D7%A1%201927%20%D7%97%D7%95%D7%A7%20%D7%94%D7%98%D7%99%D7%A1%20-%20%D7%99%D7%A0%D7%95%D7%90%D7%A8%202016.pdf
```
As rather manged in our warc:
```
Content-Disposition: inline; filename="×—×•×§ ×”×˜×™×¡ 1927 ×—×•×§ ×”×˜×™×¡ - ×™× ×•××¨ 2016.pdf"
```
I have verified that this website cannot be captured/played back with production Webrecorder. I have also verified that this Perma Link DOES play back with Perma's older pywb plackback, where we get the weird-looking:
```
Content-Disposition: inline; filename="×××§ ××××¡ 1927 ×××§ ××××¡ - ×× ×××¨ 2016.pdf"
```
That looks terrible... but when Firefox saves the file, from the playback, it correctly downloads the file as`חוק הטיס 1927 חוק הטיס - ינואר 2016⁩.pdf`
