### ISSUE TITLE
Another tempchecker race condition

### ISSUE THREAD

**Issue by rebeccacremona** [harvard-lil/perma#2614]
```
    Jun  5 15:34:58 ip-172-31-60-73 docker-compose[27175]: recorder_1    | Traceback (most recent call last):
    Jun  5 15:34:58 ip-172-31-60-73 docker-compose[27175]: recorder_1    |   File "./webrecorder/models/collection.py", line 637, in get_created_iso_date
    Jun  5 15:34:58 ip-172-31-60-73 docker-compose[27175]: recorder_1    |     dt_str = date.fromtimestamp(int(self['created_at'])).isoformat()
    Jun  5 15:34:58 ip-172-31-60-73 docker-compose[27175]: recorder_1    | TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
    Jun  5 15:34:58 ip-172-31-60-73 docker-compose[27175]: recorder_1    |
    Jun  5 15:34:58 ip-172-31-60-73 docker-compose[27175]: recorder_1    | During handling of the above exception, another exception occurred:
    Jun  5 15:34:58 ip-172-31-60-73 docker-compose[27175]: recorder_1    |
    Jun  5 15:34:58 ip-172-31-60-73 docker-compose[27175]: recorder_1    | Traceback (most recent call last):
    Jun  5 15:34:58 ip-172-31-60-73 docker-compose[27175]: recorder_1    |   File "./webrecorder/rec/storage/local.py", line 138, in delete_collection
    Jun  5 15:34:58 ip-172-31-60-73 docker-compose[27175]: recorder_1    |     dirpath = os.path.join(self.storage_root, collection.get_dir_path())
    Jun  5 15:34:58 ip-172-31-60-73 docker-compose[27175]: recorder_1    |   File "./webrecorder/models/collection.py", line 644, in get_dir_path
    Jun  5 15:34:58 ip-172-31-60-73 docker-compose[27175]: recorder_1    |     return self.get_created_iso_date() + '/' + self.my_id
    Jun  5 15:34:58 ip-172-31-60-73 docker-compose[27175]: recorder_1    |   File "./webrecorder/models/collection.py", line 639, in get_created_iso_date
    Jun  5 15:34:58 ip-172-31-60-73 docker-compose[27175]: recorder_1    |     dt_str = self['created_at'][:10]
    Jun  5 15:34:58 ip-172-31-60-73 docker-compose[27175]: recorder_1    | TypeError: 'NoneType' object is not subscriptable
```

**Comment by rebeccacremona** [comment]
The stack trace is odd, but I think this is being printed by https://github.com/webrecorder/webrecorder/blob/a39651c5da04a35f555914fd98476b9e552ab228/webrecorder/webrecorder/rec/storage/local.py#L141. I think the trace is odd because https://github.com/webrecorder/webrecorder/blob/master/webrecorder/webrecorder/models/collection.py#L635 itself contains a try/except, and the `TypeError: 'NoneType' object is not subscriptable` occurs during the `except` clause of that function.

**Comment by rebeccacremona** [comment]
Which is I believe being triggered by https://github.com/webrecorder/webrecorder/blob/26fd964977bf38c59c4905d8bc06488e8ab53100/webrecorder/webrecorder/models/collection.py#L616, which I think is being called here, https://github.com/webrecorder/webrecorder/blob/86cf440b9b91cd5111c6befec49e2fa8a63e5f25/webrecorder/webrecorder/models/user.py#L164, which is called here by the tempchecker https://github.com/webrecorder/webrecorder/blob/master/webrecorder/webrecorder/rec/tempchecker.py#L109.

So, I think, another race condition, due to the multiple tempcheckers, probably.
