### ISSUE TITLE
Rewriting sometimes duplicates protocol

### ISSUE THREAD

**Issue by rebeccacremona** [harvard-lil/perma#2632]
Example 1:
```
May 30 12:24:22 ip-172-31-58-200 docker-compose[647]: app_1         | Traceback (most recent call last):
    May 30 12:24:22 ip-172-31-58-200 docker-compose[647]: app_1         |   File "/usr/local/lib/python3.7/site-packages/pywb-2.3.0.dev0-py3.7.egg/pywb/utils/canonicalize.py", line 41, in canonicalize
    May 30 12:24:22 ip-172-31-58-200 docker-compose[647]: app_1         |     key = surt.surt(url)
    May 30 12:24:22 ip-172-31-58-200 docker-compose[647]: app_1         |   File "/usr/local/lib/python3.7/site-packages/surt/surt.py", line 73, in surt
    May 30 12:24:22 ip-172-31-58-200 docker-compose[647]: app_1         |     hurl = canonicalizer(handyurl.parse(url), **options)
    May 30 12:24:22 ip-172-31-58-200 docker-compose[647]: app_1         |   File "/usr/local/lib/python3.7/site-packages/surt/handyurl.py", line 108, in parse
    May 30 12:24:22 ip-172-31-58-200 docker-compose[647]: app_1         |     port     = o.port     or None
    May 30 12:24:22 ip-172-31-58-200 docker-compose[647]: app_1         |   File "/usr/local/lib/python3.7/urllib/parse.py", line 169, in port
    May 30 12:24:22 ip-172-31-58-200 docker-compose[647]: app_1         |     port = int(port, 10)
    May 30 12:24:22 ip-172-31-58-200 docker-compose[647]: app_1         | ValueError: invalid literal for int() with base 10: 'www.nbcdfw.com'
    May 30 12:24:22 ip-172-31-58-200 docker-compose[647]: app_1         |
    May 30 12:24:22 ip-172-31-58-200 docker-compose[647]: app_1         | During handling of the above exception, another exception occurred:
    May 30 12:24:22 ip-172-31-58-200 docker-compose[647]: app_1         |
    May 30 12:24:22 ip-172-31-58-200 docker-compose[647]: app_1         | Traceback (most recent call last):
    May 30 12:24:22 ip-172-31-58-200 docker-compose[647]: app_1         |   File "/usr/local/lib/python3.7/site-packages/bottle.py", line 862, in _handle
    May 30 12:24:22 ip-172-31-58-200 docker-compose[647]: app_1         |     return route.call(**args)
    May 30 12:24:22 ip-172-31-58-200 docker-compose[647]: app_1         |   File "/usr/local/lib/python3.7/site-packages/bottle.py", line 1740, in wrapper
    May 30 12:24:22 ip-172-31-58-200 docker-compose[647]: app_1         |     rv = callback(*a, **ka)
    May 30 12:24:22 ip-172-31-58-200 docker-compose[647]: app_1         |   File "./webrecorder/contentcontroller.py", line 406, in do_replay_coll
    May 30 12:24:22 ip-172-31-58-200 docker-compose[647]: app_1         |     return self.handle_routing(wb_url, user, coll, '*', type='replay-coll')
    May 30 12:24:22 ip-172-31-58-200 docker-compose[647]: app_1         |   File "./webrecorder/contentcontroller.py", line 788, in handle_routing
    May 30 12:24:22 ip-172-31-58-200 docker-compose[647]: app_1         |     resp = self.render_content(wb_url, kwargs, request.environ)
    May 30 12:24:22 ip-172-31-58-200 docker-compose[647]: app_1         |   File "/usr/local/lib/python3.7/site-packages/pywb-2.3.0.dev0-py3.7.egg/pywb/apps/rewriterapp.py", line 255, in render_content
    May 30 12:24:22 ip-172-31-58-200 docker-compose[647]: app_1         |     urlkey = canonicalize(wb_url.url)
    May 30 12:24:22 ip-172-31-58-200 docker-compose[647]: app_1         |   File "/usr/local/lib/python3.7/site-packages/pywb-2.3.0.dev0-py3.7.egg/pywb/utils/canonicalize.py", line 48, in canonicalize
    May 30 12:24:22 ip-172-31-58-200 docker-compose[647]: app_1         |     raise UrlCanonicalizeException('Invalid Url: ' + url)
    May 30 12:24:22 ip-172-31-58-200 docker-compose[647]: app_1         | pywb.utils.canonicalize.UrlCanonicalizeException: Invalid Url: http://https:www.nbcdfw.com/news/local/Alleged-Kidnapper-Now-in-FBI-Custody-510214191.html
```

Example 2:
```
 Jun 18 18:34:14 ip-172-31-59-227 docker-compose[7124]: app_1         | wr.io: 2019-06-18 18:34:14: [ERROR]: 500 (Internal Server Error) raised by https://wr.perma-archives.org/public/n7dr-upm2/20190618182226mp_/http%3Afortune.com/2014/09/26/transgender-workplace-rights-eeoc/
    Jun 18 18:34:14 ip-172-31-59-227 docker-compose[7124]: app_1         | Traceback (most recent call last):
    Jun 18 18:34:14 ip-172-31-59-227 docker-compose[7124]: app_1         |   File "/usr/local/lib/python3.7/site-packages/pywb-2.3.0.dev0-py3.7.egg/pywb/utils/canonicalize.py", line 41, in canonicalize
    Jun 18 18:34:14 ip-172-31-59-227 docker-compose[7124]: app_1         |     key = surt.surt(url)
    Jun 18 18:34:14 ip-172-31-59-227 docker-compose[7124]: app_1         |   File "/usr/local/lib/python3.7/site-packages/surt/surt.py", line 73, in surt
    Jun 18 18:34:14 ip-172-31-59-227 docker-compose[7124]: app_1         |     hurl = canonicalizer(handyurl.parse(url), **options)
    Jun 18 18:34:14 ip-172-31-59-227 docker-compose[7124]: app_1         |   File "/usr/local/lib/python3.7/site-packages/surt/handyurl.py", line 108, in parse
    Jun 18 18:34:14 ip-172-31-59-227 docker-compose[7124]: app_1         |     port     = o.port     or None
    Jun 18 18:34:14 ip-172-31-59-227 docker-compose[7124]: app_1         |   File "/usr/local/lib/python3.7/urllib/parse.py", line 169, in port
    Jun 18 18:34:14 ip-172-31-59-227 docker-compose[7124]: app_1         |     port = int(port, 10)
    Jun 18 18:34:14 ip-172-31-59-227 docker-compose[7124]: app_1         | ValueError: invalid literal for int() with base 10: 'fortune.com'
    Jun 18 18:34:14 ip-172-31-59-227 docker-compose[7124]: app_1         |
    Jun 18 18:34:14 ip-172-31-59-227 docker-compose[7124]: app_1         | During handling of the above exception, another exception occurred:
    Jun 18 18:34:14 ip-172-31-59-227 docker-compose[7124]: app_1         |
    Jun 18 18:34:14 ip-172-31-59-227 docker-compose[7124]: app_1         | Traceback (most recent call last):
    Jun 18 18:34:14 ip-172-31-59-227 docker-compose[7124]: app_1         |   File "/usr/local/lib/python3.7/site-packages/bottle.py", line 862, in _handle
    Jun 18 18:34:14 ip-172-31-59-227 docker-compose[7124]: app_1         |     return route.call(**args)
    Jun 18 18:34:14 ip-172-31-59-227 docker-compose[7124]: app_1         |   File "/usr/local/lib/python3.7/site-packages/bottle.py", line 1740, in wrapper
    Jun 18 18:34:14 ip-172-31-59-227 docker-compose[7124]: app_1         |     rv = callback(*a, **ka)
    Jun 18 18:34:14 ip-172-31-59-227 docker-compose[7124]: app_1         |   File "./webrecorder/contentcontroller.py", line 406, in do_replay_coll
    Jun 18 18:34:14 ip-172-31-59-227 docker-compose[7124]: app_1         |     return self.handle_routing(wb_url, user, coll, '*', type='replay-coll')
    Jun 18 18:34:14 ip-172-31-59-227 docker-compose[7124]: app_1         |   File "./webrecorder/contentcontroller.py", line 788, in handle_routing
    Jun 18 18:34:14 ip-172-31-59-227 docker-compose[7124]: app_1         |     resp = self.render_content(wb_url, kwargs, request.environ)
    Jun 18 18:34:14 ip-172-31-59-227 docker-compose[7124]: app_1         |   File "/usr/local/lib/python3.7/site-packages/pywb-2.3.0.dev0-py3.7.egg/pywb/apps/rewriterapp.py", line 255, in render_content
    Jun 18 18:34:14 ip-172-31-59-227 docker-compose[7124]: app_1         |     urlkey = canonicalize(wb_url.url)
    Jun 18 18:34:14 ip-172-31-59-227 docker-compose[7124]: app_1         |   File "/usr/local/lib/python3.7/site-packages/pywb-2.3.0.dev0-py3.7.egg/pywb/utils/canonicalize.py", line 48, in canonicalize
    Jun 18 18:34:14 ip-172-31-59-227 docker-compose[7124]: app_1         |     raise UrlCanonicalizeException('Invalid Url: ' + url)
    Jun 18 18:34:14 ip-172-31-59-227 docker-compose[7124]: app_1         | pywb.utils.canonicalize.UrlCanonicalizeException: Invalid Url: http://http:fortune.com/2014/09/26/transgender-workplace-rights-eeoc/
```

**Comment by bensteinberg** [comment]
Here's another one, slightly different:

```
    Jun 19 15:02:48 ip-172-31-52-240 docker-compose[7186]: app_1         | wr.io: 2019-06-19 15:02:48: [ERROR]: 500 (Internal Server Error) raised by https://wr.perma-archives.org/public/5kvx-t66c/20190619150217if_/http%3A/javascript%3A%3B/
...
    Jun 19 15:02:48 ip-172-31-52-240 docker-compose[7186]: app_1         | pywb.utils.canonicalize.UrlCanonicalizeException: Invalid Url: http://javascript:;/
```

**Comment by rebeccacremona** [comment]
Ooh, I like that one. In all cases, the first protocol is http, and the second protocol is different. Guessing the initial http is the incorrect one.

**Comment by bensteinberg** [comment]
Reviewing a few of these recently, the first exception is mostly `ValueError: invalid literal for int() with base 10: 'https'` and once `ValueError: invalid literal for int() with base 10: 'blank'`. The latter might be a little interesting -- the 500 line before the traceback is

```
    Jul  9 10:00:45 ip-172-31-61-240 docker-compose[28491]: app_1         | wr.io: 2019-07-09 10:00:45: [ERROR]: 500 (Internal Server Error) raised by https://wr.perma-archives.org/public/6trf-uujk/20190709100014if_/http%3A/about%3Ablank/
```

**Comment by matteocargnelutti** [comment]
Let's see if this also happens (sometimes) with client-side playback

**Comment by rebeccacremona** [comment]
https://github.com/harvard-lil/perma/pull/3169
