### ISSUE TITLE
Duplicate collection name

### ISSUE THREAD

**Issue by rebeccacremona** [harvard-lil/perma#2636]
What happened here?
```
    Jun 20 19:09:34 ip-172-31-52-240 docker-compose[7186]: app_1         | wr.io: 2019-06-20 19:09:34: [ERROR]: 500 (Internal Server Error) raised by https://wr.perma-archives.org:8443/api/v1/auth/ensure_login
    Jun 20 19:09:34 ip-172-31-52-240 docker-compose[7186]: app_1         | Traceback (most recent call last):
    Jun 20 19:09:34 ip-172-31-52-240 docker-compose[7186]: app_1         |   File "/usr/local/lib/python3.7/site-packages/bottle.py", line 862, in _handle
    Jun 20 19:09:34 ip-172-31-52-240 docker-compose[7186]: app_1         |     return route.call(**args)
    Jun 20 19:09:34 ip-172-31-52-240 docker-compose[7186]: app_1         |   File "/usr/local/lib/python3.7/site-packages/bottle.py", line 1740, in wrapper
    Jun 20 19:09:34 ip-172-31-52-240 docker-compose[7186]: app_1         |     rv = callback(*a, **ka)
    Jun 20 19:09:34 ip-172-31-52-240 docker-compose[7186]: app_1         |   File "./webrecorder/usercontroller.py", line 194, in ensure_login
    Jun 20 19:09:34 ip-172-31-52-240 docker-compose[7186]: app_1         |     return self.ensure_login()
    Jun 20 19:09:34 ip-172-31-52-240 docker-compose[7186]: app_1         |   File "./webrecorder/usercontroller.py", line 70, in ensure_login
    Jun 20 19:09:34 ip-172-31-52-240 docker-compose[7186]: app_1         |     public=data.get('public'))
    Jun 20 19:09:34 ip-172-31-52-240 docker-compose[7186]: app_1         |   File "./webrecorder/models/user.py", line 78, in create_collection
    Jun 20 19:09:34 ip-172-31-52-240 docker-compose[7186]: app_1         |     coll_name = self.colls.reserve_obj_name(coll_name, allow_dupe=allow_dupe)
    Jun 20 19:09:34 ip-172-31-52-240 docker-compose[7186]: app_1         |   File "./webrecorder/models/base.py", line 463, in reserve_obj_name
    Jun 20 19:09:34 ip-172-31-52-240 docker-compose[7186]: app_1         |     raise DupeNameException(name)
    Jun 20 19:09:34 ip-172-31-52-240 docker-compose[7186]: app_1         | webrecorder.models.base.DupeNameException: e7hj-mqeu
    Jun 20 19:09:34 ip-172-31-52-240 docker-compose[7186]: app_1         | [pid: 22|app: 0|req: 7458/642066] 52.91.77.74 () {58 vars in 833 bytes} [Thu Jun 20 19:09:34 2019] POST /api/v1/auth/ensure_login => generated 22 bytes in 28 msecs (HTTP/1.1 500) 3 headers in 226 bytes (3 switches on core 396)
```
Could this happen if two users hit the same GUID at appx. the same moment?

**Comment by bensteinberg** [comment]
I'm not sure this will shed any light, but I just saw one of these again, and the line just before it in the log was 

```
    Jul  9 09:20:14 ip-172-31-58-70 docker-compose[28647]: app_1         | wr.io: 2019-07-09 09:20:14: [ERROR]: 500 (Internal Server Error) raised by https://wr.perma-archives.org:8443/api/v1/auth/ensure_login
```
