### ISSUE TITLE
URL hangs when loaded via requests; curl is fine.

### ISSUE THREAD

**Issue by rebeccacremona** [harvard-lil/perma#2779]
https://www.seattletimes.com/seattle-news/education/uw-students-publish-online-rape-list-out-of-hopelessness-community-reels/

**Comment by rebeccacremona** [comment]
Repeatable on 3.5, 3.6, 3.7, and 3.8, in a clean env containing only the latest Requests. In all cases, curl works.

**Comment by rebeccacremona** [comment]
This is now behaving differently. This morning, I could retrieve it locally via requests when not on the VPN. Now, VPN on or off doesn't seem to matter. Also, this morning, the attempt to connect hung, where as now, I'm getting 
```
>>> requests.get('https://www.seattletimes.com/seattle-news/education/uw-students-publish-online-rape-list-out-of-hopelessness-community-reels/')
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/perma_web-kkDLCj8f/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/root/.local/share/virtualenvs/perma_web-kkDLCj8f/lib/python3.7/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/root/.local/share/virtualenvs/perma_web-kkDLCj8f/lib/python3.7/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.7/http/client.py", line 1336, in getresponse
    response.begin()
  File "/usr/lib/python3.7/http/client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.7/http/client.py", line 275, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response
```
Still no problem with curl or in browsers.

**Comment by rebeccacremona** [comment]
Looks like this is actually a user agent thing:
```
>>> requests.get('https://www.seattletimes.com/seattle-news/education/uw-students-publish-online-rape-list-out-of-hopelessness-community-reels/', headers={'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:75.0) Gecko/20100101 Firefox/75.0'})
<Response [200]>
>>> requests.get('https://www.seattletimes.com/seattle-news/education/uw-students-publish-online-rape-list-out-of-hopelessness-community-reels/')
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/perma_web-kkDLCj8f/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/root/.local/share/virtualenvs/perma_web-kkDLCj8f/lib/python3.7/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/root/.local/share/virtualenvs/perma_web-kkDLCj8f/lib/python3.7/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.7/http/client.py", line 1336, in getresponse
    response.begin()
  File "/usr/lib/python3.7/http/client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.7/http/client.py", line 275, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response
```

**Comment by rebeccacremona** [comment]
This is super interesting. While not on the VPN, supplying my Firefox's user agent is sufficient to get through. On the VPN, that is NOT sufficient: on the VPN, I ALSO need to supply "Accept-Language: en-US,en;q=0.5" along with my Firefox's user agent to get through. On the VPN, curl's user agent, "curl/7.64.0", is accepted without any additional headers.

**Comment by rebeccacremona** [comment]
Leaning into this.... here are three other URLs that behave similarly, except they also want `keep-alive`..... which I have working with python's `http` library, with `urllib3`, and with ONE syntax for requests.... but not the standard syntax..... getting closer.....

test URLS:
```
https://www.nasdaq.com/about/press-center/nasdaq-deliver-blockchain-e-voting-solution-strate
https://www.sacbee.com/news/politics-government/capitol-alert/article153928654.html
https://www.charlotteobserver.com/news/politics-government/election/article169129242.html
```
Code:
```
from requests import Request, Session

headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:75.0) Gecko/20100101 Firefox/75.0', 'Accept': '*/*', 'Accept-Encoding': '*', 'Accept-Language': '*', 'Connection': 'keep-alive'}

url = 'https://www.nasdaq.com/about/press-center/nasdaq-deliver-blockchain-e-voting-solution-strate'

# this hangs
with Session() as s, s.get(url, headers=headers) as r:
    print(r.status_code, r.headers, r.text)

# this succeeds
with Session() as s, s.send(Request('GET', url, headers=headers).prepare()) as r:
    print(r.status_code, r.headers, r.text)
```

**Comment by rebeccacremona** [comment]
Even closer...
```
#succeeds
with Session() as s:
    prep = Request('GET', url, headers=headers).prepare()
    r = s.send(prep, **send_kwargs)
    print(r.status_code, r.headers, r.text)

#hangs
with Session() as s:
    prep = s.prepare_request(Request('GET', url, headers=headers))
    r = s.send(prep, **send_kwargs)
    print(r.status_code, r.headers, r.text)
```

**Comment by rebeccacremona** [comment]
This is so terrible. It's judging based on the ORDER OF THE HEADERS!!!!!!!
```
>>> requests_default_ordered_headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:75.0) Gecko/20100101 Firefox/75.0', 'Accept-Encoding': '*', 'Accept': '*/*', 'Connection': 'keep-alive', 'Accept-Language': '*'}
>>> 
>>> 
>>> alphabetized_headers = {'Accept': '*/*', 'Accept-Encoding': '*', 'Accept-Language': '*', 'Connection': 'keep-alive', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:75.0) Gecko/20100101 Firefox/75.0'}
>>> 
>>> 
>>> my_ordered_headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:75.0) Gecko/20100101 Firefox/75.0', 'Accept': '*/*', 'Accept-Encoding': '*', 'Accept-Language': '*', 'Connection': 'keep-alive'}
>>> 
>>> assert requests_default_ordered_headers == alphabetized_headers == my_ordered_headers
>>> 
>>> 
>>> s.send(Request('GET', url, headers=requests_default_ordered_headers).prepare(), timeout=5)
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/perma_web-kkDLCj8f/lib/python3.7/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/root/.local/share/virtualenvs/perma_web-kkDLCj8f/lib/python3.7/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.7/http/client.py", line 1336, in getresponse
    response.begin()
  File "/usr/lib/python3.7/http/client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.7/http/client.py", line 267, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/root/.local/share/virtualenvs/perma_web-kkDLCj8f/lib/python3.7/site-packages/urllib3/contrib/pyopenssl.py", line 310, in recv_into
    raise timeout('The read operation timed out')
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/perma_web-kkDLCj8f/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/root/.local/share/virtualenvs/perma_web-kkDLCj8f/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/root/.local/share/virtualenvs/perma_web-kkDLCj8f/lib/python3.7/site-packages/urllib3/util/retry.py", line 368, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/root/.local/share/virtualenvs/perma_web-kkDLCj8f/lib/python3.7/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/root/.local/share/virtualenvs/perma_web-kkDLCj8f/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/root/.local/share/virtualenvs/perma_web-kkDLCj8f/lib/python3.7/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/root/.local/share/virtualenvs/perma_web-kkDLCj8f/lib/python3.7/site-packages/urllib3/connectionpool.py", line 306, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='www.charlotteobserver.com', port=443): Read timed out. (read timeout=5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/root/.local/share/virtualenvs/perma_web-kkDLCj8f/lib/python3.7/site-packages/requests/sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "/root/.local/share/virtualenvs/perma_web-kkDLCj8f/lib/python3.7/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='www.charlotteobserver.com', port=443): Read timed out. (read timeout=5)
>>> 
>>> 
>>> 
>>> s.send(Request('GET', url, headers=alphabetized_headers).prepare(), timeout=5)
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/perma_web-kkDLCj8f/lib/python3.7/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/root/.local/share/virtualenvs/perma_web-kkDLCj8f/lib/python3.7/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.7/http/client.py", line 1336, in getresponse
    response.begin()
  File "/usr/lib/python3.7/http/client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.7/http/client.py", line 267, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/root/.local/share/virtualenvs/perma_web-kkDLCj8f/lib/python3.7/site-packages/urllib3/contrib/pyopenssl.py", line 310, in recv_into
    raise timeout('The read operation timed out')
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/perma_web-kkDLCj8f/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/root/.local/share/virtualenvs/perma_web-kkDLCj8f/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/root/.local/share/virtualenvs/perma_web-kkDLCj8f/lib/python3.7/site-packages/urllib3/util/retry.py", line 368, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/root/.local/share/virtualenvs/perma_web-kkDLCj8f/lib/python3.7/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/root/.local/share/virtualenvs/perma_web-kkDLCj8f/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/root/.local/share/virtualenvs/perma_web-kkDLCj8f/lib/python3.7/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/root/.local/share/virtualenvs/perma_web-kkDLCj8f/lib/python3.7/site-packages/urllib3/connectionpool.py", line 306, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='www.charlotteobserver.com', port=443): Read timed out. (read timeout=5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/root/.local/share/virtualenvs/perma_web-kkDLCj8f/lib/python3.7/site-packages/requests/sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "/root/.local/share/virtualenvs/perma_web-kkDLCj8f/lib/python3.7/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='www.charlotteobserver.com', port=443): Read timed out. (read timeout=5)
>>> 
>>> 
>>> 
>>> s.send(Request('GET', url, headers=my_ordered_headers).prepare(), timeout=5)
<Response [200]>
>>> 
```

**Comment by rebeccacremona** [comment]
Okay, I went through the last 400 "invalid" capture jobs, and of those with the message, "Couldn't load URL", my custom headers in my order fixes ALL of them, except for one (which 403s, instead of hanging).

I hate it. But, I think I'm going to do it anyway. We'll see how long this hack works.

**Comment by rebeccacremona** [comment]
Let's give this another round.

**Comment by rebeccacremona** [comment]
Confirmed: these sites are once again dropping out traffic because of request headers. If we switch back to the user agent described in this ticket (which is not accurate to the Chrome we are actually using for capture), then we can get through again. Arg. Working on seeing if I can find headers that WILL work with our Chrome.

**Comment by rebeccacremona** [comment]
If we appending `(Perma.cc)` to the end, it lets us through again. Hmmmm. Do we want to just do this everywhere? Hmmmmmmmmmmmmmm.
