### ISSUE TITLE
404 via Webrecorder, success via client-side

### ISSUE THREAD

**Issue by rebeccacremona** [harvard-lil/perma#2845]
Why are all the URLs (except SeattleTimes) in https://app.frontapp.com/open/msg_hcoe3lz failing to play back via Webrecorder, but succeeding via client side? Indexing problem?

**Comment by rebeccacremona** [comment]
Local stack trace:
```
recorder_1        | Traceback (most recent call last):
recorder_1        |   File "/usr/local/lib/python3.7/site-packages/pywb-2.4.1-py3.7.egg/pywb/recorder/multifilewarcwriter.py", line 208, in _write_to_file
recorder_1        |     new_size - start)
recorder_1        |   File "./webrecorder/rec/webrecrecorder.py", line 286, in add_urls_to_index
recorder_1        |     add_urls_to_index(stream, params, filename, length))
recorder_1        |   File "/usr/local/lib/python3.7/site-packages/pywb-2.4.1-py3.7.egg/pywb/recorder/redisindexer.py", line 64, in add_urls_to_index
recorder_1        |     writer_cls=params.get('writer_cls'))
recorder_1        |   File "/usr/local/lib/python3.7/site-packages/pywb-2.4.1-py3.7.egg/pywb/indexer/cdxindexer.py", line 316, in write_cdx_index
recorder_1        |     for entry in entry_iter:
recorder_1        |   File "/usr/local/lib/python3.7/site-packages/pywb-2.4.1-py3.7.egg/pywb/indexer/archiveindexer.py", line 339, in __call__
recorder_1        |     for entry in entry_iter:
recorder_1        |   File "/usr/local/lib/python3.7/site-packages/pywb-2.4.1-py3.7.egg/pywb/indexer/archiveindexer.py", line 212, in join_request_records
recorder_1        |     for entry in entry_iter:
recorder_1        |   File "/usr/local/lib/python3.7/site-packages/pywb-2.4.1-py3.7.egg/pywb/indexer/archiveindexer.py", line 188, in create_record_iter
recorder_1        |     record.raw_stream)
recorder_1        |   File "/usr/local/lib/python3.7/site-packages/pywb-2.4.1-py3.7.egg/pywb/warcserver/inputrequest.py", line 262, in __init__
recorder_1        |     data = cgi.FieldStorage(**args)
recorder_1        |   File "/usr/local/lib/python3.7/cgi.py", line 489, in __init__
recorder_1        |     self.read_multi(environ, keep_blank_values, strict_parsing)
recorder_1        |   File "/usr/local/lib/python3.7/cgi.py", line 616, in read_multi
recorder_1        |     raise ValueError('Invalid boundary in multipart form: %r' % (ib,))
recorder_1        | ValueError: Invalid boundary in multipart form: b''
app_1             | Traceback (most recent call last):
app_1             |   File "./webrecorder/models/importer.py", line 247, in run_upload
app_1             |     self.process_pages(info, page_id_map, upload_key, total_size)
app_1             |   File "./webrecorder/models/importer.py", line 295, in process_pages
app_1             |     pages = self.detect_pages(info['coll'], info['rec'], upload_key, total_size)
app_1             |   File "./webrecorder/models/importer.py", line 469, in detect_pages
app_1             |     incr = int((total_size * 0.25) / total_cdx)
app_1             | ZeroDivisionError: float division by zero
app_1             | 
app_1             | The above exception was the direct cause of the following exception:
app_1             | 
app_1             | Traceback (most recent call last):
app_1             |   File "./webrecorder/models/importer.py", line 249, in run_upload
app_1             |     raise Exception("Exception processing pages for {}".format(first_coll.name)) from e
app_1             | Exception: Exception processing pages for sc5d-kkju
app_1             | [pid: 25|app: 0|req: 15/152] 192.168.240.7 () {40 vars in 599 bytes} [Fri Jul 23 21:16:45 2021] GET /api/v1/upload/NUYDIQSL?user=public => generated 210 bytes in 9 msecs (HTTP/1.1 200) 3 headers in 200 bytes (3 switches on core 399)
```
