### ISSUE TITLE
Worker service stops after some hours

### ISSUE THREAD

**Issue by bensteinberg** [harvard-lil/perma#3046]
The error message in the worker log is
```
[2022-03-08 17:09:55,766: ERROR/MainProcess] Control command error: OperationalError("\nCannot route message for exch
ange 'reply.celery.pidbox': Table empty or key no longer exists.\nProbably the key ('_kombu.binding.reply.celery.pidb
ox') has been removed from the Redis database.\n")
Traceback (most recent call last):
  File "/usr/local/share/perma/perma_web/.venv/lib/python3.9/site-packages/kombu/connection.py", line 454, in _rerais
e_as_library_errors
    yield
  File "/usr/local/share/perma/perma_web/.venv/lib/python3.9/site-packages/kombu/connection.py", line 533, in _ensure
d
    return fun(*args, **kwargs)
  File "/usr/local/share/perma/perma_web/.venv/lib/python3.9/site-packages/kombu/messaging.py", line 200, in _publish
    return channel.basic_publish(
  File "/usr/local/share/perma/perma_web/.venv/lib/python3.9/site-packages/kombu/transport/virtual/base.py", line 604
, in basic_publish
    return self.typeof(exchange).deliver(
  File "/usr/local/share/perma/perma_web/.venv/lib/python3.9/site-packages/kombu/transport/virtual/exchange.py", line
 70, in deliver
    for queue in _lookup(exchange, routing_key):
  File "/usr/local/share/perma/perma_web/.venv/lib/python3.9/site-packages/kombu/transport/virtual/base.py", line 714
, in _lookup
    self.get_table(exchange),
  File "/usr/local/share/perma/perma_web/.venv/lib/python3.9/site-packages/kombu/transport/redis.py", line 839, in ge
t_table
    raise InconsistencyError(NO_ROUTE_ERROR.format(exchange, key))
kombu.exceptions.InconsistencyError:
Cannot route message for exchange 'reply.celery.pidbox': Table empty or key no longer exists.
Probably the key ('_kombu.binding.reply.celery.pidbox') has been removed from the Redis database.
```
This sounds like https://github.com/celery/kombu/issues/1063 -- that is, a kombu version problem.

**Comment by bensteinberg** [comment]
We currently use kombu 4.6.11. I *think* https://github.com/celery/kombu/blob/master/Changelog.rst suggests that we can upgrade without problems.

**Comment by rebeccacremona** [comment]
As of https://github.com/harvard-lil/perma/pull/3060/commits/eb95e75a9228cfff3025ac8f7ce25f34db78a6c9, we are now running kombu 5.2.4.

Let's monitor and see if this still happens. If it does not, we can re-open.
